<?php

namespace Database\Seeders;

use App\Models\ChargeType;
use App\Models\ContainerUnit;
use App\Models\DocumentType;
use App\Models\Port;
use App\Models\ServiceType;
use Illuminate\Database\Seeder;

class MasterDataSeeder extends Seeder
{
    public function run(): void
    {
        // =============================================
        // DATA COST / JENIS BIAYA (dari DATA DEFAULT.xlsx Kolom B)
        // =============================================
        $chargeTypes = [
            'ADMINISTRATION',
            'AGENCY FEE',
            'AIR FREIGHT',
            'AIR WAYBILL',
            'AIRPORT CHARGES',
            'ALL IN CHARGES',
            'AMEND FEE',
            'AUTOMATIC MANIFEST SYSTEM',
            'BEHANDLE',
            'BILL OF LADING',
            'BL AMENDMENT',
            'BL CORRECTION',
            'BL TELEX FEE',
            'BOOKING CONTAINER FEE',
            'CANCELATION FEE',
            'CERTIFICATE OF ORIGIN',
            'CFS - CONTAINER FREIGHT STATION',
            'COLLECT FEE',
            'CONTAINER DEPOT',
            'COORDINATION COSTS',
            'COURIER',
            'CREDIT NOTE',
            'CUSTOMS CLEARANCE SPJM',
            'CUSTOMS CLEARANCE SPPB',
            'DEMMURAGE',
            'DEPO FEE',
            'DETENTION',
            'DG DECLARE',
            'DG HANDLING',
            'DG PORT',
            'DO CHARGES',
            'DOCUMENTS',
            'EMERGENCY BUNKER',
            'ENTER FEE',
            'EXTEND DO',
            'EXTRA COST',
            'FIAT',
            'FIELD FEE',
            'FORKLIFT',
            'FORM E',
            'FSC - FUEL SURCHARGE',
            'FUMIGATION',
            'GENSET',
            'HANDLING',
            'HICO',
            'IDENTIFIER FEE',
            'IMPORT TAX',
            'INSURANCE',
            'INWARD MANIFEST',
            'ISS - INTERNATIONAL SECURITY SURCHARGE',
            'JOB MONITORING',
            'LAPORAN SURVEYOR',
            'LICENSE',
            'LIFT ON/OFF',
            'LOCAL CHARGES',
            'LOCAL CHARGES BOTH',
            'LOCAL CHARGES DESTINATION',
            'LOCAL CHARGES ORIGIN',
            'LOCAL CHARGES SHIPPING LINE',
            'LSS',
            'MAGNETIC INSPECTION',
            'MECHANIC',
            'OCEAN FREIGHT',
            'OCEAN FREIGHT COLLECT',
            'OTHERS',
            'OUTWARD MANIFEST',
            'OVERBRENGEN',
            'OVERTIME',
            'OVERTIME GENSET',
            'P/U CHARGES',
            'PARKING FEE',
            'PEB',
            'PIB',
            'PICKUP CHARGES',
            'PROFIT SHARING',
            'QUARANTINE HANDLING',
            'RA',
            'REDRESS CHARGES',
            'REPAIR',
            'REPO CONTAINER',
            'SEA WAYBILL',
            'SPTNP',
            'STORAGES',
            'STRIPPING FEE',
            'STRIPPING STUFFING',
            'STUFFING FEE',
            'SURRENDERED',
            'TAX REFUND',
            'TERMINAL HANDLING FEE',
            'THC',
            'TRANSHIPMENT CHARGES',
            'TRUCK WAITING FEE',
            'TRUCKING',
            'UANG BONGKAR',
            'UANG BONGKAR LAPANGAN',
            'UNDERNAME',
            'VGM FEE',
            'WAREHOUSE',
        ];

        foreach ($chargeTypes as $name) {
            ChargeType::firstOrCreate(['name' => $name], ['is_active' => true]);
        }

        // =============================================
        // DATA UNIT / SATUAN (dari DATA DEFAULT.xlsx Kolom C)
        // =============================================
        $units = [
            '20FL', '20GP', '20OT', '20RF', '20TK',
            '40FL', '40GP', '40HQ', '40OT', '40RF',
            'Cbm', 'Cont', 'Day(s)', 'Doc', 'KG',
            'Pcs', 'Shipment', 'Trip', 'Unit', 'WM',
        ];

        foreach ($units as $name) {
            ContainerUnit::firstOrCreate(['name' => $name], ['is_active' => true]);
        }

        foreach ([
            ['code' => 'exp_sea', 'name' => 'EXPORT SEA', 'sort_order' => 10],
            ['code' => 'exp_air', 'name' => 'EXPORT AIR', 'sort_order' => 20],
            ['code' => 'imp_sea', 'name' => 'IMPORT SEA', 'sort_order' => 30],
            ['code' => 'imp_air', 'name' => 'IMPORT AIR', 'sort_order' => 40],
            ['code' => 'domestic', 'name' => 'DOMESTIC / TRUCKING', 'sort_order' => 50],
        ] as $service) {
            ServiceType::firstOrCreate(
                ['code' => $service['code']],
                ['name' => $service['name'], 'sort_order' => $service['sort_order'], 'is_active' => true]
            );
        }

        foreach ([
            ['code' => 'HBL', 'name' => 'HOUSE BL', 'service_codes' => ['exp_sea', 'imp_sea']],
            ['code' => 'MBL', 'name' => 'MASTER BL', 'service_codes' => ['exp_sea', 'imp_sea']],
            ['code' => 'HAWB', 'name' => 'HOUSE AWB', 'service_codes' => ['exp_air', 'imp_air']],
            ['code' => 'MAWB', 'name' => 'MASTER AWB', 'service_codes' => ['exp_air', 'imp_air']],
            ['code' => 'PL', 'name' => 'PACKINGLIST', 'service_codes' => ['exp_sea', 'exp_air', 'imp_sea', 'imp_air']],
            ['code' => 'INV', 'name' => 'INVOICE', 'service_codes' => ['exp_sea', 'exp_air', 'imp_sea', 'imp_air']],
            ['code' => 'DG', 'name' => 'DG DECLARE', 'service_codes' => ['exp_sea', 'exp_air']],
            ['code' => 'PEB', 'name' => 'PEB', 'service_codes' => ['exp_sea', 'exp_air']],
            ['code' => 'NPE', 'name' => 'NPE', 'service_codes' => ['exp_sea', 'exp_air']],
            ['code' => 'LS', 'name' => 'LAPORAN SURVEYOR', 'service_codes' => ['imp_sea', 'imp_air']],
            ['code' => 'COO', 'name' => 'CERTIFICATE OF ORIGIN', 'service_codes' => ['imp_sea', 'imp_air']],
            ['code' => 'ECOO', 'name' => 'E-CERTIFICATE OF ORIGIN', 'service_codes' => ['imp_sea', 'imp_air']],
        ] as $index => $document) {
            DocumentType::updateOrCreate(
                ['code' => $document['code']],
                [
                    'name' => $document['name'],
                    'category' => 'shipment',
                    'service_codes' => $document['service_codes'],
                    'is_required' => true,
                    'is_active' => true,
                    'sort_order' => ($index + 1) * 10,
                ]
            );
        }

        // =============================================
        // DATA PORT (dari DATA DEFAULT.xlsx Kolom D & E)
        // =============================================
        $ports = [
            ['name' => 'ACAJUTLA, EL SALVADOR',           'code' => 'SVAQJ', 'is_active' => true],
            ['name' => 'ADELAIDE, AUSTRALIA',             'code' => 'AUADL', 'is_active' => true],
            ['name' => 'AHMEDABAD, INDIA',                'code' => 'INAMD', 'is_active' => true],
            ['name' => 'AMBARLI, TURKEY',                 'code' => 'TRAMB', 'is_active' => true],
            ['name' => 'AMSTERDAM, NETHERLANDS',          'code' => 'NLAMS', 'is_active' => true],
            ['name' => 'ANHUI, CHINA',                    'code' => 'CNANH', 'is_active' => true],
            ['name' => 'ANNABA, ALGERIA',                 'code' => 'DZAAE', 'is_active' => true],
            ['name' => 'ANTWERP, BELGIUM',                'code' => 'BEANR', 'is_active' => true],
            ['name' => 'APAPA, NIGERIA',                  'code' => 'NGAPP', 'is_active' => true],
            ['name' => 'ASUNCION, PARAGUAY',              'code' => 'PYASU', 'is_active' => true],
            ['name' => 'ATLANTA, USA',                    'code' => 'USATL', 'is_active' => true],
            ['name' => 'AUCKLAND, NEW ZEALAND',           'code' => 'NZAKL', 'is_active' => true],
            ['name' => 'BALIKPAPAN, INDONESIA',           'code' => 'IDBPN', 'is_active' => true],
            ['name' => 'BANDAR ABBAS, IRAN',              'code' => 'IRBND', 'is_active' => true],
            ['name' => 'BANGKOK, THAILAND',               'code' => 'THBKK', 'is_active' => true],
            ['name' => 'BANJARMASIN, INDONESIA',          'code' => 'IDBDJ', 'is_active' => true],
            ['name' => 'BARCELONA, SPAIN',                'code' => 'ESBCN', 'is_active' => true],
            ['name' => 'BATAM, INDONESIA',                'code' => 'IDBTM', 'is_active' => true],
            ['name' => 'BEIJIAO, CHINA',                  'code' => 'CNBJO', 'is_active' => true],
            ['name' => 'BEIJING, CHINA',                  'code' => 'CNBJS', 'is_active' => false],
            ['name' => 'BELAWAN, INDONESIA',              'code' => 'IDBLW', 'is_active' => false],
            ['name' => 'BRISBANE, AUSTRALIA',             'code' => 'AUBNE', 'is_active' => false],
            ['name' => 'BUENAVENTURA, COLOMBIA',          'code' => 'COBUN', 'is_active' => false],
            ['name' => 'BUSAN, KOREA',                    'code' => 'KRPUS', 'is_active' => false],
            ['name' => 'CALIFORNIA, USA',                 'code' => 'USLAX', 'is_active' => false],
            ['name' => 'CARTAGENA, COLOMBIA',             'code' => 'COCTG', 'is_active' => false],
            ['name' => 'CASABLANCA, MOROCCO',             'code' => 'MACAS', 'is_active' => false],
            ['name' => 'CAT LAI, VIETNAM',                'code' => 'VNSGN', 'is_active' => false],
            ['name' => 'CDG (PARIS), FRANCE',             'code' => 'FRCDG', 'is_active' => false],
            ['name' => 'CHATTOGRAM, BANGLADESH',          'code' => 'BDCGP', 'is_active' => false],
            ['name' => 'CHENNAI, INDIA',                  'code' => 'INMAA', 'is_active' => false],
            ['name' => 'CHICAGO, USA',                    'code' => 'USCHI', 'is_active' => false],
            ['name' => 'CHITTAGONG, BANGLADESH',          'code' => 'BDCGP', 'is_active' => false],
            ['name' => 'CHONGQING, CHINA',                'code' => 'CNCKG', 'is_active' => false],
            ['name' => 'CIREBON, INDONESIA',              'code' => 'IDCBN', 'is_active' => false],
            ['name' => 'COCHIN, INDIA',                   'code' => 'INCOK', 'is_active' => false],
            ['name' => 'COLOMBO, SRI LANKA',              'code' => 'LKCMB', 'is_active' => false],
            ['name' => 'COLON, PANAMA',                   'code' => 'PAONX', 'is_active' => false],
            ['name' => 'COPENHAGEN, DENMARK',             'code' => 'DKCPH', 'is_active' => false],
            ['name' => 'CZECH REPUBLIC',                  'code' => 'CZPRG', 'is_active' => false],
            ['name' => 'DACHAN BAY, CHINA',               'code' => 'CNDCB', 'is_active' => false],
            ['name' => 'DALIAN, CHINA',                   'code' => 'CNDLC', 'is_active' => false],
            ['name' => 'DALLAS, TEXAS, USA',              'code' => 'USDAL', 'is_active' => false],
            ['name' => 'DILI, TIMOR LESTE',               'code' => 'TLDIL', 'is_active' => false],
            ['name' => 'DONGGUAN, CHINA',                 'code' => 'CNDGG', 'is_active' => false],
            ['name' => 'DUBAI, UAE',                      'code' => 'AEDXB', 'is_active' => false],
            ['name' => 'FELIXTOWE, UK',                   'code' => 'GBFXT', 'is_active' => false],
            ['name' => 'FLORENCE, ITALY',                 'code' => 'ITFLR', 'is_active' => false],
            ['name' => 'FLORIDA, USA',                    'code' => 'USMIA', 'is_active' => false],
            ['name' => 'FOS SUR MER, FRANCE',             'code' => 'FRFOS', 'is_active' => false],
            ['name' => 'FOSHAN, CHINA',                   'code' => 'CNFOS', 'is_active' => false],
            ['name' => 'FRANKFURT, GERMANY',              'code' => 'DEFRA', 'is_active' => false],
            ['name' => 'FUZHOU, CHINA',                   'code' => 'CNFOC', 'is_active' => false],
            ['name' => 'GAOSHA, CHINA',                   'code' => 'CNGSH', 'is_active' => false],
            ['name' => 'GDANSK, POLAND',                  'code' => 'PLGDN', 'is_active' => false],
            ['name' => 'GDYNIA, POLAND',                  'code' => 'PLGDY', 'is_active' => false],
            ['name' => 'GENEVA, SWITZERLAND',             'code' => 'CHGVA', 'is_active' => false],
            ['name' => 'GENOA, ITALY',                    'code' => 'ITGOA', 'is_active' => false],
            ['name' => 'GOTHENBURG, SWEDEN',              'code' => 'SEGOT', 'is_active' => false],
            ['name' => 'GUANGDONG, CHINA',                'code' => 'CNCAN', 'is_active' => false],
            ['name' => 'GUANGXI, CHINA',                  'code' => 'CNNNG', 'is_active' => false],
            ['name' => 'GUANGZHOU, CHINA',                'code' => 'CNCAN', 'is_active' => false],
            ['name' => 'GUAYAQUIL, ECUADOR',              'code' => 'ECGYE', 'is_active' => false],
            ['name' => 'HAINAN, CHINA',                   'code' => 'CNHAK', 'is_active' => false],
            ['name' => 'HAIPHONG, VIETNAM',               'code' => 'VNHPH', 'is_active' => false],
            ['name' => 'HAMBURG, GERMANY',                'code' => 'DEHAM', 'is_active' => false],
            ['name' => 'HANGZHOU, ZHEJIANG, CHINA',       'code' => 'CNHZH', 'is_active' => false],
            ['name' => 'HO CHI MINH, VIETNAM',           'code' => 'VNSGN', 'is_active' => false],
            ['name' => 'HONG KONG, CHINA',                'code' => 'HKHKG', 'is_active' => false],
            ['name' => 'HUANGPU, CHINA',                  'code' => 'CNHPU', 'is_active' => false],
            ['name' => 'HUMEN, CHINA',                    'code' => 'CNHUM', 'is_active' => false],
            ['name' => 'INCHEON, SOUTH KOREA',            'code' => 'KRINC', 'is_active' => false],
            ['name' => 'ISTANBUL, TURKEY',                'code' => 'TRIST', 'is_active' => false],
            ['name' => 'JAKARTA, INDONESIA',              'code' => 'IDTPP', 'is_active' => false],
            ['name' => 'JEBEL ALI, UAE',                  'code' => 'AEJEA', 'is_active' => false],
            ['name' => 'JEDDAH, SAUDI ARABIA',            'code' => 'SAJED', 'is_active' => false],
            ['name' => 'JIANGMEN NEW PORT, CHINA',        'code' => 'CNJMN', 'is_active' => false],
            ['name' => 'KAOHSIUNG, TAIWAN',               'code' => 'TWKHH', 'is_active' => false],
            ['name' => 'KEELUNG, TAIWAN',                 'code' => 'TWKEL', 'is_active' => false],
            ['name' => 'KHORRAMSHAHR, IRAN',              'code' => 'IRKHO', 'is_active' => false],
            ['name' => 'KLAIPEDA, LITHUANIA',             'code' => 'LTKLJ', 'is_active' => false],
            ['name' => 'KOBE, JAPAN',                     'code' => 'JPUKB', 'is_active' => false],
            ['name' => 'KOTA KINABALU, MALAYSIA',         'code' => 'MYBKI', 'is_active' => false],
            ['name' => 'KUALA LUMPUR, MALAYSIA',          'code' => 'MYPKG', 'is_active' => false],
            ['name' => 'KWANGYANG, KOREA',                'code' => 'KRKAN', 'is_active' => false],
            ['name' => 'LABUAN, MALAYSIA',                'code' => 'MYLBU', 'is_active' => false],
            ['name' => 'LAEM CHABANG, THAILAND',          'code' => 'THLCH', 'is_active' => false],
            ['name' => 'LATKRABANG, THAILAND',            'code' => 'THLKB', 'is_active' => false],
            ['name' => 'LE HAVRE, FRANCE',                'code' => 'FRLEH', 'is_active' => false],
            ['name' => 'LELIU, CHINA',                    'code' => 'CNLEL', 'is_active' => false],
            ['name' => 'LIANYUNGANG, CHINA',              'code' => 'CNLYG', 'is_active' => false],
            ['name' => 'LISBON, PORTUGAL',                'code' => 'PTLIS', 'is_active' => false],
            ['name' => 'LJUBLJANA, SLOVENIA',             'code' => 'SILJU', 'is_active' => false],
            ['name' => 'LONDON, UK',                      'code' => 'GBLON', 'is_active' => false],
            ['name' => 'LONGBEACH, USA',                  'code' => 'USLGB', 'is_active' => false],
            ['name' => 'LOS ANGELES, USA',                'code' => 'USLAX', 'is_active' => false],
            ['name' => 'MADRID, SPAIN',                   'code' => 'ESMAD', 'is_active' => false],
            ['name' => 'MAFANG, CHINA',                   'code' => 'CNMFG', 'is_active' => false],
            ['name' => 'MANILA, PHILIPPINES',             'code' => 'PHMNL', 'is_active' => false],
            ['name' => 'MARSEILLE, FRANCE',               'code' => 'FRMRS', 'is_active' => false],
            ['name' => 'MEDAN, INDONESIA',                'code' => 'IDMES', 'is_active' => false],
            ['name' => 'MELBOURNE, AUSTRALIA',            'code' => 'AUMEL', 'is_active' => false],
            ['name' => 'MEMPHIS, USA',                    'code' => 'USMEM', 'is_active' => false],
            ['name' => 'MEXICO CITY, MEXICO',             'code' => 'MXMEX', 'is_active' => false],
            ['name' => 'MILAN, ITALY',                    'code' => 'ITMIL', 'is_active' => false],
            ['name' => 'MISURATA, LIBYA',                 'code' => 'LYMRA', 'is_active' => false],
            ['name' => 'MOISALL, GERMANY',                'code' => 'DEMOI', 'is_active' => false],
            ['name' => 'MONTEVIDEO, URUGUAY',             'code' => 'UYMVD', 'is_active' => false],
            ['name' => 'MOSCOW, RUSSIA',                  'code' => 'RUMOW', 'is_active' => false],
            ['name' => 'MUARA, BRUNEI',                   'code' => 'MUMUA', 'is_active' => false],
            ['name' => 'MUMBAI, INDIA',                   'code' => 'INBOM', 'is_active' => false],
            ['name' => 'MUNICH, GERMANY',                 'code' => 'DEMUC', 'is_active' => false],
            ['name' => 'NAGOYA, JAPAN',                   'code' => 'JPNGO', 'is_active' => false],
            ['name' => 'NANSHA, CHINA',                   'code' => 'CNNHA', 'is_active' => false],
            ['name' => 'NEW DELHI, INDIA',                'code' => 'INDEL', 'is_active' => false],
            ['name' => 'NEW YORK, USA',                   'code' => 'USNYC', 'is_active' => false],
            ['name' => 'NHAVA SHEVA, INDIA',              'code' => 'INNSA', 'is_active' => false],
            ['name' => 'NINGBO, CHINA',                   'code' => 'CNNGB', 'is_active' => false],
            ['name' => 'OSAKA, JAPAN',                    'code' => 'JPOSA', 'is_active' => false],
            ['name' => 'PANJANG, INDONESIA',              'code' => 'IDPNJ', 'is_active' => false],
            ['name' => 'PASIR GUDANG, MALAYSIA',          'code' => 'MYPGU', 'is_active' => false],
            ['name' => 'PEKANBARU, INDONESIA',            'code' => 'IDPKU', 'is_active' => false],
            ['name' => 'PHNOM PENH, CAMBODIA',            'code' => 'KHPNH', 'is_active' => false],
            ['name' => 'PORT KLANG NORTH, MALAYSIA',      'code' => 'MYPKG', 'is_active' => false],
            ['name' => 'PORT KLANG, MALAYSIA',            'code' => 'MYPKG', 'is_active' => false],
            ['name' => 'PORT LOUIS, MAURITIUS',           'code' => 'MUPLU', 'is_active' => false],
            ['name' => 'PORTLAND, USA',                   'code' => 'USPDX', 'is_active' => false],
            ['name' => 'PUERTO CALDERA, COSTA RICA',      'code' => 'CRCLD', 'is_active' => false],
            ['name' => 'PUERTO QUETZAL, GUATEMALA',       'code' => 'GTPRQ', 'is_active' => false],
            ['name' => 'PUERTO SEGURO FLUVIAL, PARAGUAY', 'code' => 'PYPSF', 'is_active' => false],
            ['name' => 'PYONGTAEK, KOREA',                'code' => 'KRPPT', 'is_active' => false],
            ['name' => 'QINGDAO, CHINA',                  'code' => 'CNTAO', 'is_active' => false],
            ['name' => 'QINZHOU, CHINA',                  'code' => 'CNQZH', 'is_active' => false],
            ['name' => 'QUANZHOU, CHINA',                 'code' => 'CNQZHO','is_active' => false],
            ['name' => 'RAVENNA PORT, ITALY',             'code' => 'ITRAN', 'is_active' => false],
            ['name' => 'RIGA, LATVIA',                    'code' => 'LVRIX', 'is_active' => false],
            ['name' => 'ROTTERDAM, NETHERLANDS',          'code' => 'NLRTM', 'is_active' => false],
            ['name' => 'SAIGON, VIETNAM',                 'code' => 'VNSGN', 'is_active' => false],
            ['name' => 'SALVADOR, BRAZIL',                'code' => 'BRSSA', 'is_active' => false],
            ['name' => 'SAN JUAN, PUERTO RICO',           'code' => 'PRSJU', 'is_active' => false],
            ['name' => 'SAN PEDRO SULA, HONDURAS',        'code' => 'HNSAP', 'is_active' => false],
            ['name' => 'SANSHUI, CHINA',                  'code' => 'CNSHU', 'is_active' => false],
            ['name' => 'SAVANNAH, USA',                   'code' => 'USSAV', 'is_active' => false],
            ['name' => 'SCHUTTORF, GERMANY',              'code' => 'DESCU', 'is_active' => false],
            ['name' => 'SEMARANG, INDONESIA',             'code' => 'IDSRG', 'is_active' => false],
            ['name' => 'SHANGHAI, CHINA',                 'code' => 'CNSHA', 'is_active' => false],
            ['name' => 'SHANTOU, CHINA',                  'code' => 'CNSWA', 'is_active' => false],
            ['name' => 'SHEKOU, CHINA',                   'code' => 'CNSHK', 'is_active' => false],
            ['name' => 'SHENZHEN, CHINA',                 'code' => 'CNSZX', 'is_active' => false],
            ['name' => 'SHUNDE NEW PORT, CHINA',          'code' => 'CNSUD', 'is_active' => false],
            ['name' => 'SIHANOUKVILLE, CAMBODIA',         'code' => 'KHSKV', 'is_active' => false],
            ['name' => 'SINGAPORE, SINGAPORE',            'code' => 'SGP',   'is_active' => false],
            ['name' => 'SOEKARNO HATTA, INDONESIA',       'code' => 'IDCGK', 'is_active' => false],
            ['name' => 'SOKHNA, EGYPT',                   'code' => 'EGSOK', 'is_active' => false],
            ['name' => 'SOUTHAMPTON, UK',                 'code' => 'GBSOU', 'is_active' => false],
            ['name' => 'STABIO, SWITZERLAND',             'code' => 'CHSTB', 'is_active' => false],
            ['name' => 'STOCKHOLM-ARLANDA, SWEDEN',       'code' => 'SEARN', 'is_active' => false],
            ['name' => 'SURABAYA, INDONESIA',             'code' => 'IDSUB', 'is_active' => false],
            ['name' => 'SUVA, FIJI ISLANDS',              'code' => 'FJSVA', 'is_active' => false],
            ['name' => 'SVAY RIENG, CAMBODIA',            'code' => 'KHSRG', 'is_active' => false],
            ['name' => 'SYDNEY, AUSTRALIA',               'code' => 'AUSDY', 'is_active' => false],
            ['name' => 'TAICHUNG, TAIWAN',                'code' => 'TWTXG', 'is_active' => false],
            ['name' => 'TAIPEI, TAIWAN',                  'code' => 'TWTPE', 'is_active' => false],
            ['name' => 'TAN CANG HIEP PHUOC PORT, VIETNAM','code' => 'VNTCH','is_active' => false],
            ['name' => 'TANJUNG PRIOK, INDONESIA',        'code' => 'IDTPP', 'is_active' => false],
            ['name' => 'TAURANGA, NEW ZEALAND',           'code' => 'NZTRG', 'is_active' => false],
            ['name' => 'THESSALONIKI, GREECE',            'code' => 'GRSKG', 'is_active' => false],
            ['name' => 'TIANJIN, CHINA',                  'code' => 'CNTSN', 'is_active' => false],
            ['name' => 'TOKYO, JAPAN',                    'code' => 'TYO',   'is_active' => false],
            ['name' => 'TRIESTE, ITALY',                  'code' => 'ITTRS', 'is_active' => false],
            ['name' => 'TUNIS, TUNISIA',                  'code' => 'TNTUN', 'is_active' => false],
            ['name' => 'TURKMENBASHY, TURKMENISTAN',      'code' => 'TMKRW', 'is_active' => false],
            ['name' => 'TUTICORIN, INDIA',                'code' => 'INTUT', 'is_active' => false],
            ['name' => 'VALENCIA, SPAIN',                 'code' => 'ESVLC', 'is_active' => false],
            ['name' => 'VANCOUVER, CANADA',               'code' => 'CAVAN', 'is_active' => false],
            ['name' => 'VENICE, ITALY',                   'code' => 'ITVCE', 'is_active' => false],
            ['name' => 'WARSAW, POLAND',                  'code' => 'PLWAW', 'is_active' => false],
            ['name' => 'WENZHOU, CHINA',                  'code' => 'CNWNZ', 'is_active' => false],
            ['name' => 'WUHAN, CHINA',                    'code' => 'WUH',   'is_active' => false],
            ['name' => 'XIAMEN, CHINA',                   'code' => 'XMN',   'is_active' => false],
            ['name' => 'XIAOLAN, CHINA',                  'code' => 'CNXIA', 'is_active' => false],
            ['name' => 'XINGANG, CHINA',                  'code' => 'CNXNG', 'is_active' => false],
            ['name' => 'YANGON, MYANMAR',                 'code' => 'RGN',   'is_active' => false],
            ['name' => 'YANGZHOU, CHINA',                 'code' => 'CNYKP', 'is_active' => false],
            ['name' => 'ZHAPU, CHINA',                    'code' => 'CNZHA', 'is_active' => false],
            ['name' => 'ZHONGSHAN, CHINA',                'code' => 'CNZSN', 'is_active' => false],
            ['name' => 'ZHUHAI, CHINA',                   'code' => 'CNZUH', 'is_active' => false],
            ['name' => 'ZURICH, SWITZERLAND',             'code' => 'CHZRH', 'is_active' => false],
        ];

        foreach ($ports as $port) {
            Port::firstOrCreate(
                ['name' => $port['name']],
                ['code' => $port['code'], 'is_active' => $port['is_active']]
            );
        }
    }
}
