@extends('layouts.app')
@section('title','Rincian Biaya Job')
@section('content')
<div class="page-heading"><div><p class="eyebrow">{{ $job->number }} · {{ config('operations.job_statuses.'.$job->status) }}</p><h1>Biaya pekerjaan</h1><p>{{ $job->subject }}</p></div><div class="action-group"><a class="button button-secondary" href="{{ route('jobs.show',$job) }}">Detail job</a>@can('create',[\App\Models\JobCost::class,$job])<a class="button button-primary" href="{{ route('jobs.costs.create',$job) }}">+ Tambah biaya</a>@endcan</div></div>
@if($job->status!=='open')<div class="info-note">Pencatatan dan finalisasi biaya hanya tersedia saat job berstatus Open.</div>@endif
<div class="section-heading"><h2>Ringkasan seluruh biaya job</h2><span class="subtle">Draft + Final · Sebelum pajak</span></div>
<div class="stats-grid">@foreach(['temporary'=>['Temporary','wallet','blue'],'provision_cost'=>['Modal provision','briefcase','amber'],'provision_sell'=>['Nilai jual provision','file','green'],'profit'=>['Estimasi profit','chart','purple']] as $field=>[$label,$icon,$color])<article class="stat-card cost-stat"><div class="stat-top"><span>{{ $label }}</span><span class="stat-icon {{ $color }}"><x-icon :name="$icon"/></span></div><strong class="cost-amount">Rp {{ \App\Support\Money::format($summary['all'][$field]) }}</strong></article>@endforeach</div>
<div class="cost-progress"><span><strong>{{ $summary['draft']['count'] }}</strong> biaya Draft</span><span><strong>{{ $summary['final']['count'] }}</strong> biaya Final</span><span>Margin provision <strong>{{ \App\Support\Money::format($summary['all']['margin']) }}%</strong></span></div>
<div class="job-tabs" style="display:flex;gap:8px;flex-wrap:wrap;margin:20px 0;">
@foreach([''=>'Semua Biaya','payment_request'=>'Payment Request','reimbursement'=>'Reimbursement','debit_note'=>'Debit Note','credit_note'=>'Credit Note'] as $value=>$label)
<a href="{{ route('jobs.costs.index', $job).($value ? '?category='.$value : '') }}" class="button {{ request('category', '') === $value ? 'button-primary' : 'button-secondary' }}">{{ $label }}</a>
@endforeach
</div>
<section class="panel"><form class="filter-bar" method="GET"><select name="category" aria-label="Kategori transaksi"><option value="">Semua transaksi</option>@foreach(['payment_request'=>'Payment Request','reimbursement'=>'Reimbursement','debit_note'=>'Debit Note','credit_note'=>'Credit Note'] as $value=>$label)<option value="{{ $value }}" @selected(request('category')===$value)>{{ $label }}</option>@endforeach</select><select name="status" aria-label="Status biaya"><option value="">Semua status biaya</option>@foreach(config('operations.cost_statuses') as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select><button class="button button-primary">Terapkan</button><a class="text-link" href="{{ route('jobs.costs.index',$job) }}">Reset</a></form>
<div class="table-scroll"><table><thead><tr><th>Nomor / Tanggal</th><th>Uraian / Transaksi</th><th class="money">Total modal (IDR)</th><th class="money">Total jual (IDR)</th><th>Status</th><th>Pembayaran</th><th>Aksi</th></tr></thead><tbody>@forelse($costs as $cost)<tr><td><strong>{{ $cost->number }}</strong>@if(($cost->currency ?? 'IDR') !== 'IDR')<span class="status-badge status-active" style="font-size:10.5px;padding:2px 6px;margin-left:4px;">{{ $cost->currency }}</span>@endif<br><small>{{ $cost->cost_date->format('d/m/Y') }}</small></td><td>{{ Str::limit($cost->description,40) }}<br><small>{{ match($cost->cost_category) {'reimbursement'=>'Reimbursement','debit_note'=>'Debit Note','credit_note'=>'Credit Note',default=>'Payment Request'} }}@if(($cost->currency ?? 'IDR') !== 'IDR') · Kurs {{ \App\Support\Money::format($cost->exchange_rate) }}@endif @if($cost->quotation_id) · <a class="text-link" href="{{ route('quotations.show', $cost->quotation_id) }}">bersumber dari quotation</a>@endif</small></td><td class="money">{{ \App\Support\Money::format($cost->total_cost) }}@if(($cost->currency ?? 'IDR') !== 'IDR')<br><small class="subtle">{{ $cost->currency }} {{ \App\Support\Money::format((float)($cost->foreign_total_cost ?? ($cost->total_cost / ($cost->exchange_rate ?: 1)))) }}</small>@endif</td><td class="money">{{ \App\Support\Money::format($cost->total_price) }}@if(($cost->currency ?? 'IDR') !== 'IDR')<br><small class="subtle">{{ $cost->currency }} {{ \App\Support\Money::format((float)($cost->foreign_total_price ?? ($cost->total_price / ($cost->exchange_rate ?: 1)))) }}</small>@endif</td><td><span class="status-badge status-{{ $cost->status }}">{{ config('operations.cost_statuses.'.$cost->status) }}</span></td><td>@if($cost->paid_at)<span class="status-badge status-paid">PAID</span><br><small>{{ $cost->paid_date?->format('d/m/Y') }}</small>@else<span class="status-badge status-draft">Belum PAID</span>@endif</td><td><div class="table-actions"><a class="btn-action btn-action-primary" href="{{ route('jobs.costs.show',[$job,$cost]) }}" title="Detail dan pembayaran" data-tooltip="Detail / PAID" aria-label="Detail dan pembayaran"><x-icon name="eye"/></a></div></td></tr>@empty<tr><td colspan="7"><div class="empty-state"><x-icon name="wallet"/><h3>Belum ada transaksi yang sesuai</h3><p>Catat transaksi dari tombol Tambah Biaya.</p></div></td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $costs->links() }}</div>
</section>
<div class="cost-summary-grid">@foreach(['draft'=>'Biaya Draft — perlu diperiksa','final'=>'Biaya Final — siap untuk closing'] as $group=>$heading)<section class="panel"><div class="panel-heading"><h2>{{ $heading }}</h2></div><div class="cost-summary-body">@foreach(['temporary'=>'Temporary','provision_cost'=>'Modal provision','provision_sell'=>'Jual provision','subtotal'=>'Potensi tagihan','profit'=>'Estimasi profit'] as $field=>$label)<div class="summary-row"><span>{{ $label }}</span><strong>Rp {{ \App\Support\Money::format($summary[$group][$field]) }}</strong></div>@endforeach</div></section>@endforeach</div>
<p class="demo-note">Estimasi profit berasal dari nilai jual dikurangi modal Provision. Pengakuan pendapatan, HPP, dan tagihan dilakukan saat closing.</p>
@endsection
