@extends('layouts.app')
@section('title','Rincian Biaya Job')
@section('content')
<div class="page-heading"><div><p class="eyebrow">{{ $job->number }} · {{ config('operations.job_statuses.'.$job->status) }}</p><h1>Biaya pekerjaan</h1><p>{{ $job->subject }}</p></div><div class="action-group"><a class="button button-secondary" href="{{ route('jobs.show',$job) }}">Detail job</a>@can('create',[\App\Models\JobCost::class,$job])<a class="button button-primary" href="{{ route('jobs.costs.create',$job) }}">+ Tambah biaya</a>@endcan</div></div>
@if($job->status!=='open')<div class="info-note">Pencatatan dan finalisasi biaya hanya tersedia saat job berstatus Open.</div>@endif
<div class="section-heading"><h2>Ringkasan seluruh biaya job</h2><span class="subtle">Draft + Final · Sebelum pajak</span></div>
<div class="stats-grid">@foreach(['temporary'=>['Temporary','wallet','blue'],'provision_cost'=>['Modal provision','briefcase','amber'],'provision_sell'=>['Nilai jual provision','file','green'],'profit'=>['Estimasi profit','chart','purple']] as $field=>[$label,$icon,$color])<article class="stat-card cost-stat"><div class="stat-top"><span>{{ $label }}</span><span class="stat-icon {{ $color }}"><x-icon :name="$icon"/></span></div><strong class="cost-amount">Rp {{ \App\Support\Money::format($summary['all'][$field]) }}</strong></article>@endforeach</div>
<div class="cost-progress"><span><strong>{{ $summary['draft']['count'] }}</strong> biaya Draft</span><span><strong>{{ $summary['final']['count'] }}</strong> biaya Final</span><span>Margin provision <strong>{{ \App\Support\Money::format($summary['all']['margin']) }}%</strong></span></div>
<section class="panel"><form class="filter-bar" method="GET"><select name="type" aria-label="Jenis biaya"><option value="">Semua jenis</option>@foreach(['temporary'=>'Temporary','provision'=>'Provision'] as $value=>$label)<option value="{{ $value }}" @selected(request('type')===$value)>{{ $label }}</option>@endforeach</select><select name="status" aria-label="Status biaya"><option value="">Semua status biaya</option>@foreach(config('operations.cost_statuses') as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select><button class="button button-primary">Terapkan</button><a class="text-link" href="{{ route('jobs.costs.index',$job) }}">Reset</a></form>
<div class="table-scroll"><table><thead><tr><th>Nomor / Tanggal</th><th>Uraian / Jenis</th><th class="money">Total modal</th><th class="money">Total jual</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($costs as $cost)<tr><td><strong>{{ $cost->number }}</strong><br><small>{{ $cost->cost_date->format('d/m/Y') }}</small></td><td>{{ Str::limit($cost->description,40) }}<br><small>{{ ucfirst($cost->type) }}@if($cost->quotation_id) · <a class="text-link" href="{{ route('quotations.show', $cost->quotation_id) }}">bersumber dari quotation</a>@endif</small></td><td class="money">{{ \App\Support\Money::format($cost->total_cost) }}</td><td class="money">{{ \App\Support\Money::format($cost->total_price) }}</td><td><span class="status-badge status-{{ $cost->status }}">{{ config('operations.cost_statuses.'.$cost->status) }}</span></td><td><div class="table-actions"><a class="btn-action btn-action-primary" href="{{ route('jobs.costs.show',[$job,$cost]) }}">Detail</a></div></td></tr>@empty<tr><td colspan="6"><div class="empty-state"><x-icon name="wallet"/><h3>Belum ada biaya yang sesuai</h3><p>Catat pengeluaran aktual sebagai Temporary atau Provision.</p></div></td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $costs->links() }}</div>
</section>
<div class="cost-summary-grid">@foreach(['draft'=>'Biaya Draft — perlu diperiksa','final'=>'Biaya Final — siap untuk closing'] as $group=>$heading)<section class="panel"><div class="panel-heading"><h2>{{ $heading }}</h2></div><div class="cost-summary-body">@foreach(['temporary'=>'Temporary','provision_cost'=>'Modal provision','provision_sell'=>'Jual provision','subtotal'=>'Potensi tagihan','profit'=>'Estimasi profit'] as $field=>$label)<div class="summary-row"><span>{{ $label }}</span><strong>Rp {{ \App\Support\Money::format($summary[$group][$field]) }}</strong></div>@endforeach</div></section>@endforeach</div>
<p class="demo-note">Estimasi profit berasal dari nilai jual dikurangi modal Provision. Pengakuan pendapatan, HPP, dan tagihan dilakukan saat closing.</p>
@endsection
