@extends('layouts.app')
@section('title','Detail Biaya')
@section('content')
<div class="page-heading"><div><p class="eyebrow">{{ $job->number }} · {{ config('operations.job_statuses.'.$job->status) }}</p><h1>{{ $cost->number }}</h1><p>{{ $cost->description }}</p></div><a class="button button-secondary" href="{{ route('jobs.costs.index',$job) }}">← Kembali</a></div>
@if($cost->status==='final')<div class="info-note">Biaya sudah Final dan terkunci. Perubahan langsung serta penghapusan tidak diperbolehkan.</div>@endif
<section class="panel"><div class="panel-heading"><h2>Rincian biaya aktual</h2><span class="status-badge status-{{ $cost->status }}">{{ config('operations.cost_statuses.'.$cost->status) }}</span></div>
<dl class="detail-grid">
<div><dt>Jenis transaksi</dt><dd><strong>{{ match($cost->cost_category) { 'reimbursement' => 'Reimbursement (Temporary Payment)', 'debit_note' => 'Debit Note (Piutang Agent)', 'credit_note' => 'Credit Note (Hutang Agent)', default => 'Payment Request (Provisional Payment)' } }}</strong></dd></div><div><dt>Tanggal biaya</dt><dd>{{ $cost->cost_date->format('d/m/Y') }}</dd></div><div><dt>Jumlah / Satuan</dt><dd>{{ \App\Support\Money::format($cost->quantity) }} {{ $cost->unit }}</dd></div>
<div><dt>Modal per unit</dt><dd>Rp {{ \App\Support\Money::format($cost->unit_cost) }}</dd></div><div><dt>Nilai jual per unit</dt><dd>Rp {{ \App\Support\Money::format($cost->unit_price) }}</dd></div><div><dt>Penerima / vendor</dt><dd>{{ $cost->payee ?? '—' }}</dd></div>
<div><dt>Nomor bukti / referensi</dt><dd>{{ $cost->reference ?? '—' }}</dd></div>@if($cost->quotation_id)<div><dt>Referensi quotation</dt><dd><a class="text-link" href="{{ route('quotations.show', $cost->quotation_id) }}">{{ $cost->quotation->number }}</a>@if($cost->quotation_item_id)<br>Item ke-{{ $cost->quotationItem->position }} · {{ $cost->quotationItem->description }}@endif</dd></div>@endif<div><dt>Dibuat oleh</dt><dd>{{ $cost->creator?->name }}<br>{{ $cost->created_at->format('d/m/Y H:i') }}</dd></div><div><dt>Finalisasi</dt><dd>{{ $cost->finalizer?->name ?? 'Belum difinalisasi' }}<br>{{ $cost->finalized_at?->format('d/m/Y H:i') }}</dd></div>
</dl>
@if($cost->notes)<div class="detail-notes"><strong>Catatan</strong><br>{{ $cost->notes }}</div>@endif
<div class="summary-box"><div class="summary-row"><span>Total modal</span><strong>Rp {{ \App\Support\Money::format($cost->total_cost) }}</strong></div><div class="summary-row summary-total"><span>Total jual</span><strong>Rp {{ \App\Support\Money::format($cost->total_price) }}</strong></div></div>
<div class="info-note" style="margin-top:16px;"><strong>Status Pembayaran Vendor:</strong> @if($cost->paid_at) PAID · {{ $cost->paid_date?->format('d/m/Y') }} · {{ $cost->paymentAccount?->name }} @elseif(in_array($cost->cost_category,['payment_request','reimbursement'])) Belum PAID — sudah tercatat sebagai Hutang Vendor sejak Draft. @else Belum PAID — tercatat sebagai Hutang Vendor saat Job ditutup. @endif</div>
</section>
<div class="quote-actions">@can('update',$cost)<a class="button button-secondary" href="{{ route('jobs.costs.edit',[$job,$cost]) }}">Edit biaya Draft</a>@endcan
@can('finalize',$cost)<form method="POST" action="{{ route('jobs.costs.finalize',[$job,$cost]) }}" data-confirm="Finalisasi biaya ini? Setelah Final, biaya tidak dapat diedit atau dihapus langsung.">@csrf<input type="hidden" name="job_version" value="{{ $job->lock_version }}"><input type="hidden" name="lock_version" value="{{ $cost->lock_version }}"><button class="button button-primary">Finalisasi biaya</button></form>@endcan
@can('approve',$cost)<form method="POST" action="{{ route('jobs.costs.approve',[$job,$cost]) }}" data-confirm="Setujui transaksi ini untuk Closing Job?">@csrf<input type="hidden" name="job_version" value="{{ $job->lock_version }}"><input type="hidden" name="lock_version" value="{{ $cost->lock_version }}"><button class="button button-primary">Setujui untuk Closing</button></form>@endcan
@can('delete',$cost)<form method="POST" action="{{ route('jobs.costs.destroy',[$job,$cost]) }}" data-confirm="Hapus biaya Draft ini dari perhitungan job?">@csrf @method('DELETE')<input type="hidden" name="job_version" value="{{ $job->lock_version }}"><input type="hidden" name="lock_version" value="{{ $cost->lock_version }}"><button class="button button-danger">Hapus biaya Draft</button></form>@endcan
@if(!$cost->paid_at && ($job->status==='closed' || in_array($cost->cost_category,['payment_request','reimbursement'])))<form method="POST" action="{{ route('jobs.costs.pay',[$job,$cost]) }}" class="transition-form" style="margin-top:16px;max-width:640px;">@csrf<input type="hidden" name="job_version" value="{{ $job->lock_version }}"><div class="form-grid"><div class="field"><label>Tanggal PAID</label><input type="date" name="paid_date" value="{{ today()->toDateString() }}" max="{{ today()->toDateString() }}" required></div><div class="field"><label>Bank asal / Kas</label><select name="payment_account_id" required><option value="">Pilih rekening</option>@foreach($bankAccounts as $account)<option value="{{ $account->id }}">{{ $account->code }} — {{ $account->name }}</option>@endforeach</select></div><div class="field"><label>Potong PPh 23</label><input type="number" name="pph23_amount" min="0" max="{{ $cost->total_cost }}" step="0.01" value="{{ $cost->pph23_amount ?? 0 }}"></div></div><button class="button button-primary">PAID</button></form>@elseif(!$cost->paid_at)<p class="form-help">Biaya biasa dapat ditandai PAID setelah Closing Job. Payment Request dan Reimbursement dapat dibayar sejak Draft.</p>@endif
</div>
@endsection
