@extends('layouts.app')
@section('title',$account->exists?'Edit Akun':'Tambah Akun')
@section('content')
<div class="page-heading"><div><p class="eyebrow">AKUNTANSI</p><h1>{{ $account->exists?'Edit akun':'Tambah akun' }}</h1><p>Gunakan kode unik dan tipe akun yang sesuai.</p></div><a class="text-link" href="{{ route('accounts.index') }}">Kembali ke daftar</a></div>
<section class="panel form-panel"><form class="data-form" method="POST" action="{{ $account->exists?route('accounts.update',$account):route('accounts.store') }}">@csrf @if($account->exists) @method('PUT') @endif<input type="hidden" name="lock_version" value="{{ old('lock_version',$account->lock_version ?? 0) }}">
<div class="form-grid"><div class="field"><label for="code">Kode akun <span class="required">*</span></label><input id="code" name="code" value="{{ old('code',$account->code) }}" required maxlength="20" placeholder="1106"></div><div class="field"><label for="name">Nama akun <span class="required">*</span></label><input id="name" name="name" value="{{ old('name',$account->name) }}" required maxlength="255" placeholder="Nama akun"></div><div class="field"><label for="type">Tipe akun <span class="required">*</span></label><select id="type" name="type" required>@foreach(config('accounting.types') as $key=>$label)<option value="{{ $key }}" @selected(old('type',$account->type)===$key)>{{ $label }}</option>@endforeach</select></div></div>
<div class="form-actions"><a class="button button-secondary" href="{{ route('accounts.index') }}">Batal</a><button class="button button-primary">Simpan akun</button></div></form></section>
@if($account->exists)<section class="archive-panel"><div><h3>Arsipkan akun</h3><p>Akun yang masih digunakan mapping harus diganti terlebih dahulu.</p></div><form method="POST" action="{{ route('accounts.destroy',$account) }}" data-confirm="Arsipkan akun ini?">@csrf @method('DELETE')<input type="hidden" name="lock_version" value="{{ $account->lock_version }}"><button class="button button-danger">Arsipkan</button></form></section>@endif
@endsection
