@extends('layouts.app')
@section('title','Detail Vendor')
@section('content')
<div class="page-heading"><div><p class="eyebrow">MASTER DATA</p><h1>{{ $vendor->code }}</h1><p>{{ $vendor->name }}</p></div><a class="text-link" href="{{ route('vendors.index') }}">Kembali ke daftar</a></div>
@if($vendor->trashed())<div class="info-note"><strong>Vendor nonaktif.</strong> Tidak dapat dipilih untuk transaksi baru. <form method="POST" action="{{ route('vendors.restore',$vendor) }}" data-confirm="Aktifkan kembali vendor ini?" class="inline-form">@csrf<input type="hidden" name="lock_version" value="{{ $vendor->lock_version }}"><button class="text-link">Aktifkan kembali</button></form></div>@endif
<section class="panel"><div class="panel-heading"><h2>Informasi vendor</h2><div class="action-group">@if($vendor->trashed())<span class="status-badge status-inactive">Diarsipkan</span>@elseif($vendor->is_active)<span class="status-badge status-active">Aktif</span>@else<span class="status-badge status-inactive">Nonaktif</span>@endif<a class="button button-secondary button-sm" href="{{ route('vendors.edit',$vendor) }}">Edit</a>@if(!$vendor->trashed())<form method="POST" action="{{ route('vendors.toggle',$vendor) }}" data-confirm="{{ $vendor->is_active?'Nonaktifkan':'Aktifkan' }} vendor ini?">@csrf<input type="hidden" name="lock_version" value="{{ $vendor->lock_version }}"><button class="button button-{{ $vendor->is_active?'secondary':'primary' }} button-sm">{{ $vendor->is_active?'Nonaktifkan':'Aktifkan' }}</button></form>@endif</div></div>
<dl class="detail-grid"><div><dt>Kode vendor</dt><dd>{{ $vendor->code }}</dd></div><div><dt>Kategori utama</dt><dd>{{ config('operations.vendor_types.'.$vendor->type) ?? $vendor->type }}</dd></div><div><dt>Kategori tambahan</dt><dd>@foreach($vendor->categoryLabels() as $label)<span class="badge-pill">{{ $label }}</span>@endforeach</dd></div><div><dt>PIC</dt><dd>{{ $vendor->pic ?? '—' }}</dd></div><div><dt>Email</dt><dd>{{ $vendor->email ?? '—' }}</dd></div><div><dt>Telepon</dt><dd>{{ $vendor->phone ?? '—' }}</dd></div><div><dt>NPWP</dt><dd>{{ $vendor->tax_number ?? '—' }}</dd></div><div><dt>Negara</dt><dd>{{ $vendor->country ?? '—' }}</dd></div><div><dt>Alamat</dt><dd>{{ $vendor->address ?? '—' }}</dd></div><div><dt>Catatan</dt><dd>{{ $vendor->notes ?? '—' }}</dd></div></dl></section>
<section class="panel"><div class="panel-heading"><h2>Tarif trucking</h2><a class="text-link" href="{{ route('pricing.trucking.index') }}">Lihat tarif</a></div>
<div class="table-scroll"><table><thead><tr><th>Rute</th><th>Kontainer</th><th>Overweight</th><th class="money">Tarif</th><th>Berlaku</th><th>Status</th></tr></thead><tbody>@forelse($vendor->truckingPrices as $price)<tr><td>{{ $price->port_origin }} → {{ $price->destination }}</td><td>{{ strtoupper($price->container_type) }}</td><td>{{ $price->overweight?'Ya':'—' }}</td><td class="money">{{ $price->currency }} {{ number_format((float)$price->price, 0, ',', '.') }}</td><td>{{ $price->effective_date->format('d/m/Y') }}@if($price->effective_until)<br><small class="muted-cell">s.d. {{ $price->effective_until->format('d/m/Y') }}</small>@endif</td><td>@if($price->is_active)<span class="status-badge status-active">Aktif</span>@else<span class="status-badge status-inactive">Nonaktif</span>@endif</td></tr>@empty<tr><td colspan="6"><div class="empty-state"><h3>Belum ada tarif trucking</h3><p>Tambahkan tarif pada menu Tarif Trucking.</p></div></td></tr>@endforelse</tbody></table></div></section>
@endsection