<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        @page{margin:28px 34px}body{font-family:DejaVu Sans,sans-serif;color:#26364f;font-size:11px;line-height:1.55}.header{border-bottom:2px solid #0f1f3d;padding-bottom:14px;margin-bottom:24px}.company{font-size:19px;font-weight:700;color:#163f8f}.muted{color:#6f7f96}.title{font-size:24px;letter-spacing:2px;text-align:right;color:#1f3e72;margin-top:-44px}.grid{width:100%;margin-bottom:18px}.col{float:left;width:48%;margin-right:2%;vertical-align:top}.clear{clear:both}.box{border:1px solid #dce5f2;padding:12px}table{width:100%;border-collapse:collapse;margin-top:14px}th{background:#f1f5fb;color:#50647f;text-align:left;font-size:9px;padding:8px;border:1px solid #dce5f2}td{padding:8px;border:1px solid #e6edf6}.money{text-align:right}.summary{width:42%;margin-left:58%}.sign{width:100%;margin-top:42px}.sign-col{float:left;width:50%;text-align:center}.line{border-top:1px solid #aeb9c8;margin:54px 45px 0;padding-top:8px}.footer{position:fixed;bottom:-8px;left:0;right:0;text-align:center;font-size:9px;color:#8a97aa}
    </style>
</head>
<body>
<div class="header"><div class="company">JobFinance Demo Company</div><div class="muted">Jakarta, Indonesia<br>finance@jobfinance.test · +62 21 0000 0000 · jobfinance.test</div><div class="title">QUOTATION</div></div>
<div class="grid"><div class="col"><div class="box"><strong>Customer</strong><br>{{ $quotation->customer_snapshot['name'] }}<br>{{ $quotation->customer_snapshot['address'] ?? '' }}<br>{{ $quotation->customer_snapshot['email'] ?? '' }}</div></div><div class="col"><div class="box"><strong>Quotation No</strong>: {{ $quotation->number }}<br><strong>Date</strong>: {{ $quotation->quotation_date->format('d/m/Y') }}<br><strong>Valid Until</strong>: {{ $quotation->valid_until->format('d/m/Y') }}<br><strong>Project</strong>: {{ $quotation->subject }}</div></div><div class="clear"></div></div>
<table><thead><tr><th>No</th><th>Description</th><th>Qty</th><th>Unit</th><th class="money">Unit Price</th><th class="money">Amount</th></tr></thead><tbody>@foreach($quotation->items as $item)<tr><td>{{ $loop->iteration }}</td><td>{{ $item->description }}@if($item->pricing_source === 'trucking')<br/><span style="font-size:8px;color:#6f7f96">Tarif trucking · {{ $item->pricing_snapshot['port_origin'] }} → {{ $item->pricing_snapshot['destination'] }} · {{ strtoupper($item->container_type) }}@if(($item->pricing_snapshot['currency'] ?? 'IDR') !== 'IDR') · {{ $item->pricing_snapshot['currency'] }} {{ \App\Support\Money::format($item->pricing_snapshot['price']) }} @ kurs {{ \App\Support\Money::format($item->pricing_snapshot['exchange_rate']) }}@endif</span>@elseif($item->container_type)<br/><span style="font-size:8px;color:#6f7f96">{{ strtoupper($item->container_type) }}@if($item->overweight) +OW@endif@if($item->gross_weight !== null) · BW {{ $item->gross_weight }} kg@endif@if($item->volume !== null) · {{ $item->volume }} m³@endif</span>@endif</td><td>{{ \App\Support\Money::format($item->quantity) }}</td><td>{{ $item->unit }}</td><td class="money">Rp {{ \App\Support\Money::format($item->unit_price) }}</td><td class="money">Rp {{ \App\Support\Money::format($item->total_price) }}</td></tr>@endforeach</tbody></table>
<table class="summary"><tr><td>Subtotal</td><td class="money">Rp {{ \App\Support\Money::format($quotation->subtotal) }}</td></tr><tr><td>Discount</td><td class="money">Rp {{ \App\Support\Money::format($quotation->discount ?? 0) }}</td></tr><tr><td>Tax</td><td class="money">Rp {{ \App\Support\Money::format($quotation->tax_amount ?? 0) }}@if(($quotation->tax_rate ?? 0) > 0) <small>({{ $quotation->tax_rate }}%)</small>@endif</td></tr><tr><td><strong>Grand Total</strong></td><td class="money"><strong>Rp {{ \App\Support\Money::format($quotation->grand_total ?? $quotation->subtotal) }}</strong></td></tr></table>
<p><strong>Terms & Conditions</strong><br>{{ $quotation->notes ?: 'Harga berlaku sesuai tanggal validitas quotation. Pajak dan biaya tambahan mengikuti kesepakatan tertulis.' }}</p>
<p><strong>Payment Terms</strong><br>Pembayaran mengikuti invoice yang diterbitkan setelah pekerjaan dikonfirmasi.</p>
<div class="sign"><div class="sign-col"><div class="line">Prepared By<br>{{ $quotation->creator?->name ?? '-' }}</div></div><div class="sign-col"><div class="line">Approved By<br>{{ $quotation->approver?->name ?? '-' }}</div></div><div class="clear"></div></div>
<div class="footer">Page <script type="text/php">if(isset($pdf)){echo $PAGE_NUM.' of '.$PAGE_COUNT;}</script></div>
</body>
</html>
