@extends('layouts.app')
@section('title', 'Dashboard Finance')
@section('content')
<div class="role-hero"><div><span class="eyebrow" style="color:#b9c9e6">WORKSPACE FINANCE</span><h2>Keuangan lebih terkontrol.</h2><p>Prioritaskan invoice jatuh tempo dan kurs aktif hari ini.</p></div><a class="button button-white" href="{{ route('invoices.index') }}">Buka Invoice <x-icon name="arrow"/></a></div>
<div class="stats-grid"><article class="stat-card"><div class="stat-top"><span>Invoice belum lunas</span><span class="stat-icon amber"><x-icon name="wallet"/></span></div><strong class="stat-number">{{ $unpaidInvoices->count() }}</strong><p>Invoice yang perlu ditindaklanjuti.</p></article><article class="stat-card"><div class="stat-top"><span>Jatuh tempo terdekat</span><span class="stat-icon red"><x-icon name="calendar"/></span></div><strong class="stat-number">{{ $unpaidInvoices->first()?->due_date?->format('d/m') ?? '—' }}</strong><p>Periksa daftar invoice untuk detail.</p></article><article class="stat-card"><div class="stat-top"><span>Kurs Mingguan</span><span class="stat-icon blue"><x-icon name="chart"/></span></div><strong class="stat-number">{{ $weeklyPricing?->currency ?? '—' }}</strong><p>{{ $weeklyPricing ? \App\Support\Money::format($weeklyPricing->exchange_rate) : 'Belum tersedia' }}</p></article></div>
<div class="finance-strip" style="margin-bottom:20px">@foreach(['Temporary Final (Job Open)'=>$temporaryBalance,'Provision Final (Job Open)'=>$provisionBalance,'Pendapatan'=>$revenueBalance,'HPP'=>$cogsBalance] as $label=>$amount)<div><span>{{ $label }}</span><strong>Rp {{ \App\Support\Money::format($amount) }}</strong></div>@endforeach</div>
<section class="panel" style="margin-bottom:20px"><div class="panel-heading"><div><h2>Prioritas penagihan</h2><p>Invoice yang jatuh tempo lebih dulu perlu ditindaklanjuti.</p></div><span class="status-chip">{{ $unpaidInvoices->count() }} unpaid</span></div><div style="padding:0 22px 20px"><div class="progress-track"><i style="width:{{ min(100, $unpaidInvoices->count()*15) }}%"></i></div></div></section>
<section class="panel" style="margin-bottom:20px"><div class="panel-heading"><div><h2>Umur piutang</h2><p>Distribusi invoice berdasarkan jatuh tempo.</p></div></div><div class="mini-chart"><div class="bar-item"><div class="bar" style="height:{{ max(7,$invoiceAging['current']*18) }}%;background:#0f1f3d"></div><small>Saat ini<br>{{ $invoiceAging['current'] }}</small></div><div class="bar-item"><div class="bar" style="height:{{ max(7,$invoiceAging['overdue_1_30']*18) }}%;background:#b91c1c"></div><small>1–30 hari<br>{{ $invoiceAging['overdue_1_30'] }}</small></div><div class="bar-item"><div class="bar" style="height:{{ max(7,$invoiceAging['overdue_30_plus']*18) }}%;background:#7f1d1d"></div><small>>30 hari<br>{{ $invoiceAging['overdue_30_plus'] }}</small></div></div></section>
<section class="panel"><div class="panel-heading"><div><h2>Invoice yang perlu dibayar</h2><p>Urut berdasarkan tanggal jatuh tempo.</p></div><a class="text-link" href="{{ route('invoices.index') }}">Lihat semua invoice</a></div><div class="table-scroll"><table><thead><tr><th>Invoice</th><th>Jatuh tempo</th><th class="money">Sisa</th></tr></thead><tbody>@forelse($unpaidInvoices as $invoice)<tr><td>{{ $invoice->number }}</td><td>{{ $invoice->due_date->format('d/m/Y') }}</td><td class="money">Rp {{ \App\Support\Money::format($invoice->balance) }}</td></tr>@empty<tr><td colspan="3">Tidak ada invoice terbuka.</td></tr>@endforelse</tbody></table></div></section>
@endsection
