@extends('layouts.app')
@section('title', 'Dashboard Finance Manager')
@section('content')
<div class="role-hero"><div><span class="eyebrow" style="color:#b9c9e6">WORKSPACE FINANCE MANAGER</span><h2>Profit terlihat jelas.</h2><p>Bandingkan pendapatan dan profit dari job yang sudah closing.</p></div><a class="button button-white" href="{{ route('reports.profit-per-job') }}">Lihat Analisis <x-icon name="arrow"/></a></div>
<div class="stats-grid"><article class="stat-card"><span>Profit Job</span><strong class="stat-number"><small>Rp</small> {{ \App\Support\Money::format($profitBalance) }}</strong><p>Total profit dari job closing.</p></article><article class="stat-card"><span>Pendapatan</span><strong class="stat-number"><small>Rp</small> {{ \App\Support\Money::format($revenueBalance) }}</strong><p>Total pendapatan dari closing.</p></article><article class="stat-card"><span>Kurs Mingguan</span><strong class="stat-number">{{ $weeklyPricing?->currency ?? '—' }}</strong><p>{{ $weeklyPricing ? \App\Support\Money::format($weeklyPricing->exchange_rate) : 'Belum tersedia' }}</p></article></div>
<div class="finance-strip" style="margin-bottom:20px">@foreach(['Temporary Final (Job Open)'=>$temporaryBalance,'Provision Final (Job Open)'=>$provisionBalance,'Pendapatan'=>$revenueBalance,'HPP'=>$cogsBalance] as $label=>$amount)<div><span>{{ $label }}</span><strong>Rp {{ \App\Support\Money::format($amount) }}</strong></div>@endforeach</div>
<section class="panel"><div class="panel-heading"><div><h2>Pendapatan & profit</h2><p>Performa enam bulan terakhir.</p></div><span class="status-chip">6 bulan</span></div><div class="mini-chart">@php $maxRevenue=max(1,$monthlyPerformance->max(fn($row)=>(float)$row['revenue'])); @endphp @foreach($monthlyPerformance as $month)<div class="bar-item"><div class="bar" style="height:{{ max(7,((float)$month['revenue']/$maxRevenue)*100) }}%" title="Pendapatan Rp {{ \App\Support\Money::format($month['revenue']) }} · Profit Rp {{ \App\Support\Money::format($month['profit']) }}"></div><small>{{ $month['label'] }}</small></div>@endforeach</div></section>
<section class="panel"><div class="panel-heading"><div><h2>Akses laporan</h2><p>Gunakan laporan ini untuk analisis keuangan.</p></div></div><div class="form-actions"><a class="button button-primary" href="{{ route('reports.profit-per-job') }}">Profit per Job</a><a class="button button-secondary" href="{{ route('reports.profit-monthly') }}">Profit Bulanan</a></div></section>
@endsection
