@extends('layouts.app')
@section('title', 'Dashboard Sales')
@section('content')
<div class="role-hero"><div><span class="eyebrow" style="color:#b9c9e6">WORKSPACE SALES</span><h2>Quotation lebih cepat.</h2><p>Buat penawaran, cek approval, dan gunakan kurs terbaru.</p></div><a class="button button-white" href="{{ route('quotations.create') }}">Buat Quotation <x-icon name="arrow"/></a></div>
<div class="stats-grid"><article class="stat-card"><span>Quotation Draft</span><strong class="stat-number">{{ $widgets['quotes']['draft'] ?? 0 }}</strong><p>Belum disetujui.</p></article><article class="stat-card"><span>Menunggu Persetujuan</span><strong class="stat-number">{{ ($widgets['quotes']['submitted'] ?? 0) + ($widgets['quotes']['revision'] ?? 0) }}</strong><p>Perlu ditindaklanjuti.</p></article><article class="stat-card"><span>Kurs Mingguan</span><strong class="stat-number">{{ $weeklyPricing?->currency ?? '—' }}</strong><p>{{ $weeklyPricing ? \App\Support\Money::format($weeklyPricing->exchange_rate) : 'Belum tersedia' }}</p></article></div>
<section class="panel" style="margin-bottom:20px"><div class="panel-heading"><div><h2>Pipeline quotation</h2><p>Posisi quotation yang sedang berjalan.</p></div></div><div style="padding:0 22px 20px"><div class="progress-track"><i style="width:{{ min(100, (($widgets['quotes']['approved'] ?? 0) + ($widgets['quotes']['converted'] ?? 0))*12) }}%"></i></div></div></section>
<section class="panel" style="margin-bottom:20px"><div class="panel-heading"><div><h2>Funnel quotation</h2><p>Pergerakan quotation dari draft sampai menjadi job.</p></div></div><div class="mini-chart"><div class="bar-item"><div class="bar" style="height:{{ max(7,($widgets['quotes']['draft'] ?? 0)*15) }}%"></div><small>Draft<br>{{ $widgets['quotes']['draft'] ?? 0 }}</small></div><div class="bar-item"><div class="bar" style="height:{{ max(7,($widgets['quotes']['submitted'] ?? 0)*15) }}%"></div><small>Diajukan<br>{{ $widgets['quotes']['submitted'] ?? 0 }}</small></div><div class="bar-item"><div class="bar" style="height:{{ max(7,($widgets['quotes']['approved'] ?? 0)*15) }}%"></div><small>Disetujui<br>{{ $widgets['quotes']['approved'] ?? 0 }}</small></div><div class="bar-item"><div class="bar" style="height:{{ max(7,($widgets['quotes']['converted'] ?? 0)*15) }}%"></div><small>Job<br>{{ $widgets['quotes']['converted'] ?? 0 }}</small></div></div></section>
<section class="panel"><div class="panel-heading"><h2>Quotation saya</h2><a class="text-link" href="{{ route('quotations.index') }}">Lihat semua</a></div><div class="table-scroll"><table><thead><tr><th>Nomor</th><th>Customer</th><th>Status</th></tr></thead><tbody>@forelse($widgets['myQuotes'] ?? [] as $quote)<tr><td>{{ $quote->number }}</td><td>{{ $quote->customer_snapshot['name'] ?? '—' }}</td><td>{{ $quote->status->label() }}</td></tr>@empty<tr><td colspan="3">Belum ada quotation.</td></tr>@endforelse</tbody></table></div></section>
@endsection
