@extends('layouts.app')
@section('title', 'Profil Saya')
@section('content')
<div class="page-heading"><div><p class="eyebrow">ACCOUNT CENTER</p><h1>Profil Saya</h1><p>Kelola informasi pribadi, akses role, dan keamanan akun Anda.</p></div><span class="role-badge">{{ $user->role?->label ?? 'Tanpa role' }}</span></div>
<div class="profile-layout">
<section class="panel profile-card"><div class="profile-cover"></div><div class="profile-avatar">{{ mb_strtoupper(mb_substr($user->name, 0, 1)) }}</div><div class="profile-identity"><h2>{{ $user->name }}</h2><p>{{ $user->email }}</p><span class="status-badge status-active">Akun aktif</span></div><div class="profile-access"><div><small>Role akses</small><strong>{{ $user->role?->label ?? 'Tanpa role' }}</strong></div><div><small>Bergabung</small><strong>{{ $user->created_at?->format('d M Y') ?? '—' }}</strong></div></div><div class="profile-permissions"><small>Yang dapat Anda akses</small>@forelse($user->role?->permissions ?? [] as $permission)<span>{{ $permission->label ?? ucwords(str_replace(['.','_'],' ', $permission->name)) }}</span>@empty<span>Belum ada permission</span>@endforelse</div></section>
<section class="panel"><div class="panel-heading"><div><h2>Data pribadi</h2><p>Informasi identitas dan kontak akun.</p></div></div><form class="data-form" method="POST" action="{{ route('profile.update') }}">@csrf @method('PUT')<div class="form-grid"><div class="field"><label>Nama lengkap</label><input name="name" value="{{ old('name',$user->name) }}" required></div><div class="field"><label>Email login</label><input value="{{ $user->email }}" disabled><small class="form-help">Email dikelola administrator.</small></div><div class="field"><label>NIK</label><input name="nik" value="{{ old('nik',$user->nik) }}" maxlength="32" placeholder="Nomor Induk Kependudukan"></div><div class="field"><label>Nomor telepon</label><input name="phone" value="{{ old('phone',$user->phone) }}" maxlength="40" placeholder="08xxxxxxxxxx"></div><div class="field"><label>Tanggal lahir</label><input type="date" name="birth_date" value="{{ old('birth_date',$user->birth_date?->format('Y-m-d')) }}"></div><div class="field"><label>Jenis kelamin</label><select name="gender"><option value="">Pilih</option><option value="male" @selected(old('gender',$user->gender)==='male')>Laki-laki</option><option value="female" @selected(old('gender',$user->gender)==='female')>Perempuan</option></select></div><div class="field"><label>Jabatan</label><input name="position" value="{{ old('position',$user->position) }}" placeholder="Contoh: Finance Staff"></div><div class="field"><label>Departemen</label><input name="department" value="{{ old('department',$user->department) }}"></div><div class="field span-2"><label>Alamat</label><textarea name="address" rows="3" maxlength="2000">{{ old('address',$user->address) }}</textarea></div><div class="field"><label>Kontak darurat</label><input name="emergency_contact" value="{{ old('emergency_contact',$user->emergency_contact) }}"></div><div class="field"><label>Telepon darurat</label><input name="emergency_phone" value="{{ old('emergency_phone',$user->emergency_phone) }}"></div></div><div class="form-actions"><button class="button button-primary">Simpan profil</button></div></form></section>
<section class="panel"><div class="panel-heading"><div><h2>Keamanan akun</h2><p>Ganti password secara berkala untuk menjaga akses.</p></div><x-icon name="lock"/></div><form class="data-form" method="POST" action="{{ route('profile.password') }}">@csrf @method('PUT')<div class="form-grid"><div class="field"><label>Password saat ini</label><input type="password" name="current_password" required autocomplete="current-password"></div><div></div><div class="field"><label>Password baru</label><input type="password" name="password" minlength="10" required autocomplete="new-password"><small class="form-help">Minimal 10 karakter, huruf besar/kecil, dan angka.</small></div><div class="field"><label>Konfirmasi password</label><input type="password" name="password_confirmation" minlength="10" required autocomplete="new-password"></div></div><div class="form-actions"><button class="button button-primary">Ubah password</button></div></form></section>
</div>
@endsection
