@extends('layouts.app')
@section('title','Job Order')
@section('content')
<div class="page-heading"><div><p class="eyebrow">OPERASIONAL</p><h1>Job Order</h1><p>Pantau status pengiriman, transportasi, dan penanggung jawab setiap pekerjaan.</p></div>@can('quotations.manage')<a class="button button-primary" href="{{ route('quotations.index') }}">Lihat quotation</a>@endcan</div>
<section class="panel"><form class="filter-bar" method="GET">
<input name="search" value="{{ $search }}" placeholder="Cari nomor, nama pekerjaan, atau customer" aria-label="Cari job">
<input name="date_from" type="date" value="{{ $dateFrom }}" aria-label="Dari tanggal">
<input name="date_to" type="date" value="{{ $dateTo }}" aria-label="Sampai tanggal">
<select name="service_type" aria-label="Layanan"><option value="">Semua layanan</option>@foreach(config('operations.service_types') as $key=>$label)<option value="{{ $key }}" @selected($serviceType===$key)>{{ $label }}</option>@endforeach</select>
<select name="sales_id" aria-label="Sales"><option value="">Semua sales</option>@foreach($assignees as $user)<option value="{{ $user->id }}" @selected($salesId===$user->id)>{{ $user->name }}</option>@endforeach</select>
<select name="cs_id" aria-label="Customer service"><option value="">Semua CS</option>@foreach($assignees as $user)<option value="{{ $user->id }}" @selected($csId===$user->id)>{{ $user->name }}</option>@endforeach</select>
<select name="status" aria-label="Status job"><option value="">Semua status</option>@foreach(config('operations.job_statuses') as $value=>$label)<option value="{{ $value }}" @selected(request('status')===$value)>{{ $label }}</option>@endforeach</select>
<button class="button button-primary">Cari</button><a class="text-link" href="{{ route('jobs.index') }}">Reset</a>
</form>
<div class="table-scroll"><table><thead><tr><th>No Job / Tanggal</th><th>Customer / Pekerjaan</th><th>BL/AWB</th><th>Service</th><th>Quote</th><th>Sales / CS</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($jobs as $job)<tr><td><strong>{{ $job->number }}</strong><br><small>{{ $job->job_date->format('d/m/Y') }}</small></td><td>{{ $job->quotation_snapshot['customer']['name'] }}<br><small>{{ Str::limit($job->subject,45) }}</small></td><td>{{ $job->bl_number ?: ($job->awb_number ?: '—') }}</td><td>{{ config('operations.service_types.'.$job->service_type) ?? '—' }}</td><td>@can('quotations.manage')<a href="{{ route('quotations.show', $job->quotation_id) }}" class="text-link">{{ $job->quotation_snapshot['number'] ?? '—' }}</a>@else{{ $job->quotation_snapshot['number'] ?? '—' }}@endcan</td><td>{{ $job->sales?->name ?? '—' }}@if($job->cs)<br><small>CS: {{ $job->cs->name }}</small>@endif</td><td><span class="status-badge status-{{ $job->status }}">{{ config('operations.job_statuses.'.$job->status) }}</span>@if($job->status==='open' && $job->etaApproaching())<br><span class="status-badge" style="background:#fef2f2;color:#b91c1c;border-color:#fecaca;margin-top:4px;display:inline-block">ETA Dekat</span>@endif</td><td><div class="action-group"><a class="text-link" href="{{ route('jobs.show',$job) }}">Detail</a>@can('update',$job)<a class="text-link" href="{{ route('jobs.edit',$job) }}">Edit</a>@endcan</div></td></tr>@empty<tr><td colspan="8"><div class="empty-state"><x-icon name="briefcase"/><h3>Belum ada Job Order yang sesuai</h3><p>Job tersedia setelah quotation disetujui dan dikonversi.</p></div></td></tr>@endforelse</tbody></table></div><div class="pagination">{{ $jobs->links() }}</div></section>
@endsection