@extends('layouts.app')
@section('title','Detail Job Order')
@section('content')
<div class="page-heading"><div><p class="eyebrow">JOB ORDER</p><h1>{{ $job->number }}</h1><p>{{ $job->subject }}</p></div><a class="text-link" href="{{ route('jobs.index') }}">Kembali ke daftar</a></div>
<div class="quote-actions">@can('update',$job)<a class="button button-secondary" href="{{ route('jobs.edit',$job) }}">Edit operasional</a>@endcan
@can('open',$job)<form method="POST" action="{{ route('jobs.open',$job) }}" data-confirm="Buka job ini? Finance dapat mulai mencatat biaya setelah job berstatus Open.">@csrf<input type="hidden" name="lock_version" value="{{ $job->lock_version }}"><button class="button button-primary">Buka job</button></form>@endcan
@can('costs.manage')<a class="button button-primary" href="{{ route('jobs.costs.index',$job) }}"><x-icon name="wallet"/>Lihat biaya aktual</a>@endcan
@can('jobs.close')@if($job->status==='open')<a class="button button-primary" href="{{ route('closing.create',$job) }}">Closing job</a>@endif @endcan
@can('invoices.manage')@if($job->invoice)<a class="button button-primary" href="{{ route('invoices.show',$job->invoice) }}">Lihat invoice</a>@endif @endcan</div>
<section class="panel"><div class="panel-heading"><h2>Informasi pekerjaan</h2><span class="status-badge status-{{ $job->status }}">{{ config('operations.job_statuses.'.$job->status) }}</span></div>
<dl class="detail-grid"><div><dt>Customer</dt><dd>{{ $job->quotation_snapshot['customer']['name'] }}</dd></div><div><dt>Quotation asal</dt><dd>@can('quotations.manage')<a class="text-link" href="{{ route('quotations.show',$job->quotation) }}">{{ $job->quotation_snapshot['number'] }}</a>@else{{ $job->quotation_snapshot['number'] }}@endcan</dd></div><div><dt>Tanggal job</dt><dd>{{ $job->job_date->format('d/m/Y') }}</dd></div>
<div><dt>Jenis layanan</dt><dd>{{ config('operations.service_types.'.$job->service_type) ?? '—' }}</dd></div><div><dt>Asal → Tujuan</dt><dd>{{ $job->origin ?? '—' }} → {{ $job->destination ?? '—' }}</dd></div><div><dt>Target selesai</dt><dd>{{ $job->expected_completion_date?->format('d/m/Y') ?? '—' }}</dd></div>
<div><dt>Referensi pengiriman</dt><dd>{{ $job->shipment_reference ?? '—' }}</dd></div><div><dt>Job dibuka</dt><dd>{{ $job->opened_at?->format('d/m/Y H:i') ?? 'Belum dibuka' }}</dd></div>
</dl>
@if($job->cargo_description)<div class="detail-notes"><strong>Deskripsi muatan</strong><br>{{ $job->cargo_description }}</div>@endif
@if($job->operational_notes)<div class="detail-notes"><strong>Catatan operasional</strong><br>{{ $job->operational_notes }}</div>@endif
@if($job->cancellation_reason)<div class="detail-notes"><strong>Alasan pembatalan</strong><br>{{ $job->cancellation_reason }}<br>{{ $job->cancelled_at?->format('d/m/Y H:i') }}</div>@endif
</section>
<div class="section-heading"><h2>Estimasi penawaran</h2><span class="subtle">Snapshot quotation · Bukan biaya aktual</span></div>
<section class="panel"><div class="table-scroll"><table class="quote-detail-table"><thead><tr><th>Uraian</th><th>Jenis</th><th>Jumlah</th><th class="money">Estimasi modal</th><th class="money">Estimasi tagihan</th></tr></thead><tbody>@foreach($job->quotation_snapshot['items'] as $item)<tr><td>{{ $item['description'] }}</td><td>{{ ucfirst($item['type']) }}</td><td>{{ \App\Support\Money::format($item['quantity']) }} {{ $item['unit'] }}</td><td class="money">{{ \App\Support\Money::format($item['total_cost']) }}</td><td class="money">{{ \App\Support\Money::format($item['total_price']) }}</td></tr>@endforeach</tbody></table></div><div class="summary-box"><div class="summary-row"><span>Estimasi profit</span><strong>Rp {{ \App\Support\Money::format($job->quotation_snapshot['totals']['profit']) }}</strong></div><div class="summary-row summary-total"><span>Total sebelum pajak</span><strong>Rp {{ \App\Support\Money::format($job->quotation_snapshot['totals']['subtotal']) }}</strong></div></div></section>
@can('cancel',$job)<section class="panel job-cancel"><form class="transition-form" method="POST" action="{{ route('jobs.cancel',$job) }}" data-confirm="Batalkan job ini? Job hanya dapat dibatalkan jika tidak memiliki biaya aktif.">@csrf<input type="hidden" name="lock_version" value="{{ $job->lock_version }}"><label for="reason">Alasan pembatalan job</label><textarea name="reason" id="reason" rows="2" maxlength="1000" required placeholder="Jelaskan alasan pembatalan">{{ old('reason') }}</textarea><p class="form-help">Job yang masih memiliki biaya aktif tidak dapat dibatalkan.</p><button class="button button-danger">Batalkan job</button></form></section>@endcan
@endsection
