@extends('layouts.app')
@section('title','Detail Job Order')
@section('content')
<div class="page-heading"><div><p class="eyebrow">JOB ORDER</p><h1>{{ $job->number }}</h1><p>{{ $job->subject }}</p></div><a class="text-link" href="{{ route('jobs.index') }}">Kembali ke daftar</a></div>
<div class="quote-actions">@can('update',$job)<a class="button button-secondary" href="{{ route('jobs.edit',$job) }}">Edit operasional</a>@endcan
@can('open',$job)<form method="POST" action="{{ route('jobs.open',$job) }}" data-confirm="Buka job ini? Finance dapat mulai mencatat biaya setelah job berstatus Open.">@csrf<input type="hidden" name="lock_version" value="{{ $job->lock_version }}"><button class="button button-primary">Buka job</button></form>@endcan
@can('costs.manage')<a class="button button-primary" href="{{ route('jobs.costs.index',$job) }}"><x-icon name="wallet"/>Lihat biaya aktual</a>@endcan
@can('jobs.close')@if($job->status==='open')<a class="button button-primary" href="{{ route('closing.create',$job) }}">Closing job</a>@endif @endcan
@can('invoices.manage')@if($job->invoice)<a class="button button-primary" href="{{ route('invoices.show',$job->invoice) }}">Lihat invoice</a>@endif @endcan
@if($job->status==='open' && !$job->do_confirmed_at)@can('update',$job)<form method="POST" action="{{ route('jobs.confirm-do',$job) }}" data-confirm="Konfirmasi bahwa Delivery Order (DO) telah selesai?">@csrf<button class="button button-primary" style="background:#16a34a;border-color:#16a34a">DO Selesai</button></form>@endcan @elseif($job->do_confirmed_at)<span class="status-badge status-paid">DO Selesai ({{ $job->do_confirmed_at->format('d/m/Y') }})</span>@endif
</div>
<section class="panel"><div class="panel-heading"><h2>Informasi pekerjaan</h2><span class="status-badge status-{{ $job->status }}">{{ config('operations.job_statuses.'.$job->status) }}</span></div>
<dl class="detail-grid"><div><dt>Customer</dt><dd>{{ $job->quotation_snapshot['customer']['name'] }}</dd></div><div><dt>Quotation asal</dt><dd>@can('quotations.manage')<a class="text-link" href="{{ route('quotations.show',$job->quotation) }}">{{ $job->quotation_snapshot['number'] }}</a>@else{{ $job->quotation_snapshot['number'] }}@endcan</dd></div><div><dt>Tanggal job</dt><dd>{{ $job->job_date->format('d/m/Y') }}@if($job->expected_completion_date)<br><small>Target selesai: {{ $job->expected_completion_date->format('d/m/Y') }}</small>@endif</dd></div>
<div><dt>Jenis layanan</dt><dd>{{ config('operations.service_types.'.$job->service_type) ?? '—' }}</dd></div><div><dt>Pengirim</dt><dd>{{ $job->shipper_name ?? '—' }}@if($job->shipper_address)<br><small>{{ $job->shipper_address }}</small>@endif</dd></div><div><dt>Penerima</dt><dd>{{ $job->consignee_name ?? '—' }}@if($job->consignee_address)<br><small>{{ $job->consignee_address }}</small>@endif</dd></div>
<div><dt>Rute</dt><dd>@if($job->pol || $job->pod){{ $job->pol ?? '—' }} → {{ $job->pod ?? '—' }}@else{{ $job->origin ?? '—' }} → {{ $job->destination ?? '—' }}@endif</dd></div><div><dt>ETD / ETA</dt><dd>{{ $job->etd?->format('d/m/Y') ?? '—' }} → {{ $job->eta?->format('d/m/Y') ?? '—' }} @if($job->status==='open' && $job->etaApproaching()) <span class="status-badge" style="background:#fef2f2;color:#b91c1c;border-color:#fecaca">Mendekati ETA</span> @endif</dd></div>
<div><dt>Sarana pengangkut</dt><dd>@if($job->vessel_voyage)<x-icon name="briefcase"/> {{ $job->vessel_voyage }} @endif @if($job->flight_number)@if($job->vessel_voyage)<br>@endif <strong>Penerbangan:</strong> {{ $job->flight_number }}@endif @if(! $job->vessel_voyage && ! $job->flight_number)—@endif</dd></div><div><dt>Sales / CS</dt><dd>{{ $job->sales?->name ?? '—' }}{{ $job->cs ? ' / '.$job->cs->name : '' }}</dd></div>
<div><dt>Job dibuka</dt><dd>{{ $job->opened_at?->format('d/m/Y H:i') ?? 'Belum dibuka' }}</dd></div>
</dl>
@if($job->bl_number || $job->hbl_number || $job->awb_number || $job->hawb_number || $job->shipment_reference || $job->booking_reference)<div class="detail-notes"><strong>Referensi dokumen</strong><br><table class="ref-table">@if($job->bl_number)<tr><th>BL</th><td>{{ $job->bl_number }}</td></tr>@endif @if($job->hbl_number)<tr><th>HBL</th><td>{{ $job->hbl_number }}</td></tr>@endif @if($job->awb_number)<tr><th>AWB</th><td>{{ $job->awb_number }}</td></tr>@endif @if($job->hawb_number)<tr><th>HAWB</th><td>{{ $job->hawb_number }}</td></tr>@endif @if($job->shipment_reference)<tr><th>Referensi</th><td>{{ $job->shipment_reference }}</td></tr>@endif @if($job->booking_reference)<tr><th>Booking</th><td>{{ $job->booking_reference }}</td></tr>@endif</table></div>@endif
@if($job->package_count || $job->gross_weight || $job->volume || $job->container_type || $job->cargo_description)<div class="detail-notes"><strong>Muatan</strong><br>@if($job->package_count || $job->container_type)<span class="badge-pill">{{ $job->package_count ? $job->package_count.' paket' : 'Paket: —'}}@if($job->container_type) · {{ config('operations.container_types.'.$job->container_type) ?? $job->container_type }}@endif</span> @endif @if($job->gross_weight)<span class="badge-pill">Berat: {{ \App\Support\Money::format($job->gross_weight) }} kg</span>@endif @if($job->volume)<span class="badge-pill">Volume: {{ \App\Support\Money::format($job->volume) }} cbm</span>@endif @if($job->cargo_description)<br>{{ $job->cargo_description }}@endif</div>@endif
@if($job->operational_notes)<div class="detail-notes"><strong>Catatan operasional</strong><br>{{ $job->operational_notes }}</div>@endif
@if($job->cancellation_reason)<div class="detail-notes"><strong>Alasan pembatalan</strong><br>{{ $job->cancellation_reason }}<br>{{ $job->cancelled_at?->format('d/m/Y H:i') }}</div>@endif
</section>

<div class="section-heading"><h2>Dokumen Pengiriman</h2><span class="subtle">File BL, AWB, SI, dll</span></div>
<section class="panel">
<div class="table-scroll"><table><thead><tr><th>Tipe Dokumen</th><th>Nama File</th><th>Ukuran</th><th>Waktu Upload</th><th>Aksi</th></tr></thead><tbody>@forelse($job->documents as $doc)<tr><td><span class="badge-pill">{{ $doc->documentType->code }}</span><br><small>{{ $doc->documentType->name }}</small></td><td><strong>{{ $doc->original_name }}</strong><br><small>Oleh: {{ $doc->uploader?->name ?? 'Sistem' }}</small>@if($doc->notes)<p class="form-help" style="margin-top:4px">{{ $doc->notes }}</p>@endif</td><td>{{ $doc->file_size_formatted }}</td><td>{{ $doc->created_at->format('d/m/Y H:i') }}</td><td><div class="action-group"><a class="text-link" href="{{ route('jobs.documents.download', [$job, $doc]) }}" target="_blank">Download</a>@can('update',$job)<form method="POST" action="{{ route('jobs.documents.destroy', [$job, $doc]) }}" data-confirm="Hapus dokumen ini?">@csrf @method('DELETE')<button class="text-link" style="color:#ef4444">Hapus</button></form>@endcan</div></td></tr>@empty<tr><td colspan="5"><div class="empty-state"><x-icon name="file"/><h3>Belum ada dokumen yang diupload</h3><p>Upload dokumen pengiriman terkait pekerjaan ini.</p></div></td></tr>@endforelse</tbody></table></div>
@can('update',$job)
<form class="data-form" style="margin-top:20px;padding-top:20px;border-top:1px solid #e2e8f0" method="POST" action="{{ route('jobs.documents.store',$job) }}" enctype="multipart/form-data">@csrf
<div class="form-grid">
<div class="field"><label for="document_type_id">Jenis Dokumen</label><select name="document_type_id" id="document_type_id" required><option value="">Pilih tipe dokumen</option>@foreach($documentTypes as $dt)<option value="{{ $dt->id }}">{{ $dt->code }} - {{ $dt->name }}</option>@endforeach</select></div>
<div class="field"><label for="file">File (PDF/Image/Excel/Word)</label><input type="file" name="file" id="file" required accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx,.xls,.xlsx"></div>
<div class="field span-2"><label for="notes">Keterangan Tambahan</label><input type="text" name="notes" id="notes" maxlength="255" placeholder="Opsional"></div>
</div><div class="form-actions"><button class="button button-primary">Upload Dokumen</button></div>
</form>
@endcan
</section>
<div class="section-heading"><h2>Estimasi penawaran</h2><span class="subtle">Snapshot quotation · Bukan biaya aktual</span></div>
@can('financial.view')
<section class="panel"><div class="table-scroll"><table class="quote-detail-table"><thead><tr><th>Uraian</th><th>Jenis</th><th>Jumlah</th><th class="money">Estimasi modal</th><th class="money">Estimasi tagihan</th></tr></thead><tbody>@foreach($job->quotation_snapshot['items'] as $item)<tr><td>{{ $item['description'] }}</td><td>{{ ucfirst($item['type']) }}</td><td>{{ \App\Support\Money::format($item['quantity']) }} {{ $item['unit'] }}</td><td class="money">{{ \App\Support\Money::format($item['total_cost']) }}</td><td class="money">{{ \App\Support\Money::format($item['total_price']) }}</td></tr>@endforeach</tbody></table></div><div class="summary-box"><div class="summary-row"><span>Estimasi profit</span><strong>Rp {{ \App\Support\Money::format($job->quotation_snapshot['totals']['profit']) }}</strong></div><div class="summary-row summary-total"><span>Total sebelum pajak</span><strong>Rp {{ \App\Support\Money::format($job->quotation_snapshot['totals']['subtotal']) }}</strong></div></div></section>
@else
<section class="panel"><div class="table-scroll"><table class="quote-detail-table"><thead><tr><th>Uraian</th><th>Jenis</th><th>Jumlah</th><th class="money">Estimasi tagihan</th></tr></thead><tbody>@foreach($job->quotation_snapshot['items'] as $item)<tr><td>{{ $item['description'] }}</td><td>{{ ucfirst($item['type']) }}</td><td>{{ \App\Support\Money::format($item['quantity']) }} {{ $item['unit'] }}</td><td class="money">{{ \App\Support\Money::format($item['total_price']) }}</td></tr>@endforeach</tbody></table></div><div class="summary-box"><div class="summary-row summary-total"><span>Total sebelum pajak</span><strong>Rp {{ \App\Support\Money::format($job->quotation_snapshot['totals']['subtotal']) }}</strong></div></div></section>
@endcan
@can('financial.view')
<div class="section-heading"><h2>Ringkasan keuangan</h2><span class="subtle">Biaya aktual Final · Hanya untuk Finance</span></div>
<section class="panel"><div class="cost-summary-body"><div class="summary-box">@if($summary['count'] > 0)<div class="summary-row"><span>Total modal aktual (provision)</span><strong>Rp {{ \App\Support\Money::format($summary['provision_cost']) }}</strong></div><div class="summary-row"><span>Total tagihan aktual</span><strong>Rp {{ \App\Support\Money::format($summary['provision_sell']) }}</strong></div><div class="summary-row"><span>Biaya temporary</span><strong>Rp {{ \App\Support\Money::format($summary['temporary']) }}</strong></div><div class="summary-row"><span>Laba (rugi) aktual</span><strong>Rp {{ \App\Support\Money::format($summary['profit']) }}</strong></div><div class="summary-row summary-total"><span>Margin</span><strong>{{ \App\Support\Money::format($summary['margin']) }}%</strong></div>@else<div class="empty-state"><h3>Belum ada biaya Final</h3><p>Ringkasan keuangan tampil setelah Finance mencatat dan memfinalisasi biaya.</p></div>@endif</div></div></section>
@endcan
<div class="section-heading"><h2>Riwayat status</h2><span class="subtle">Perjalanan persetujuan dan status</span></div>
<section class="panel"><div class="cost-summary-body"><ol class="approval-timeline">@forelse($job->statusHistory as $event)<li><span></span><div><strong>@if($event->from_status){{ config('operations.job_statuses.'.$event->from_status) ?? $event->from_status }} → {{ config('operations.job_statuses.'.$event->to_status) ?? $event->to_status }}@elseDibuat → {{ config('operations.job_statuses.'.$event->to_status) ?? $event->to_status }}@endif</strong><p>{{ $event->user?->name ?? 'System' }} · {{ $event->created_at->format('d/m/Y H:i') }}@if($event->note)<br>{{ $event->note }}@endif</p></div></li>@empty<li><span></span><div><strong>Tidak ada riwayat</strong><p>Riwayat akan tercatat saat job dibuat atau berubah status.</p></div></li>@endforelse</ol></div></section>
@can('cancel',$job)<section class="panel job-cancel"><form class="transition-form" method="POST" action="{{ route('jobs.cancel',$job) }}" data-confirm="Batalkan job ini? Job hanya dapat dibatalkan jika tidak memiliki biaya aktif.">@csrf<input type="hidden" name="lock_version" value="{{ $job->lock_version }}"><label for="reason">Alasan pembatalan job</label><textarea name="reason" id="reason" rows="2" maxlength="1000" required placeholder="Jelaskan alasan pembatalan">{{ old('reason') }}</textarea><p class="form-help">Job yang masih memiliki biaya aktif tidak dapat dibatalkan.</p><button class="button button-danger">Batalkan job</button></form></section>@endcan
@endsection