@extends('layouts.app')
@section('title','Reimbursement')
@section('content')
<div class="page-heading"><div><p class="eyebrow">KEUANGAN</p><h1>Reimbursement</h1><p>Catat pengeluaran pribadi karyawan, setujui, dan bayar dengan jurnal otomatis.</p></div><a class="button button-primary" href="{{ route('reimbursements.create') }}">Buat reimbursement</a></div>
<div class="document-stats">
<div class="document-stat"><span>Menunggu</span><strong>{{ $totals['pending'] ?? 0 }}</strong></div>
<div class="document-stat"><span>Disetujui</span><strong>{{ $totals['approved'] ?? 0 }}</strong></div>
<div class="document-stat"><span>Dibayar</span><strong>{{ $totals['paid'] ?? 0 }}</strong></div>
<div class="document-stat"><span>Ditolak</span><strong>{{ $totals['rejected'] ?? 0 }}</strong></div>
</div>
<section class="panel"><form class="filter-bar" method="GET"><input name="search" value="{{ $search }}" placeholder="Cari nomor, keterangan, atau karyawan" aria-label="Cari"><select name="status" aria-label="Status"><option value="">Semua status</option>@foreach(['pending'=>'Menunggu','approved'=>'Disetujui','paid'=>'Dibayar','rejected'=>'Ditolak'] as $key=>$label)<option value="{{ $key }}" @selected($status===$key)>{{ $label }}</option>@endforeach</select><select name="category" aria-label="Kategori"><option value="">Semua kategori</option>@foreach(config('jobfinance.reimbursement_categories') as $key=>$settings)<option value="{{ $key }}" @selected($category===$key)>{{ $settings['label'] }}</option>@endforeach</select><input type="date" name="date_from" value="{{ request('date_from') }}" aria-label="Dari tanggal"><input type="date" name="date_to" value="{{ request('date_to') }}" aria-label="Sampai tanggal"><button class="button button-primary">Terapkan</button><a class="text-link" href="{{ route('reimbursements.index') }}">Reset</a></form>
<div class="table-scroll"><table><thead><tr><th>Nomor</th><th>Tanggal</th><th>Kategori</th><th>Karyawan</th><th>Keterangan</th><th>Status</th><th class="money">Jumlah</th><th>Aksi</th></tr></thead><tbody>@forelse($reimbursements as $reimbursement)<tr><td><a class="text-link" href="{{ route('reimbursements.show',$reimbursement) }}">{{ $reimbursement->number }}</a></td><td>{{ $reimbursement->reimbursement_date->format('d/m/Y') }}</td><td>{{ config('jobfinance.reimbursement_categories.'.$reimbursement->category.'.label', $reimbursement->category) }}</td><td>{{ $reimbursement->employee->name }}</td><td>{{ \Illuminate\Support\Str::limit($reimbursement->description, 40) }}</td><td><span class="status-badge status-{{ $reimbursement->status }}">{{ ['pending'=>'Menunggu','approved'=>'Disetujui','paid'=>'Dibayar','rejected'=>'Ditolak'][$reimbursement->status] ?? $reimbursement->status }}</span></td><td class="money">{{ $reimbursement->currency }} {{ \App\Support\Money::format($reimbursement->amount) }}</td><td><a class="text-link" href="{{ route('reimbursements.show',$reimbursement) }}">Lihat</a></td></tr>@empty<tr><td colspan="8"><div class="empty-state"><x-icon name="wallet"/><h3>Belum ada reimbursement</h3><p>Semua pengeluaran karyawan yang tercatat tampil di sini.</p></div></td></tr>@endforelse</tbody></table></div>{{ $reimbursements->links() }}</section>
@endsection