<?php

return [
    'permissions' => [
        'dashboard.view',
        'customers.view',
        'customers.manage',
        'customers.approve',
        'coa.manage',
        'quotations.view',
        'quotations.manage',
        'quotations.approve',
        'export-documents.manage',
        'jobs.view',
        'jobs.manage',
        'jobs.confirm-do',
        'master-data.manage',
        'costs.manage',
        'jobs.close',
        'invoices.manage',
        'payments.manage',
        'journals.manage',
        'reimbursements.manage',
        'reports.view',
        'financial.view',
        'vendors.manage',
        'pricing.manage',
        'pricing.view',
        'email.manage',
        'users.view',
        'users.manage',
        'activity.view',
    ],
    'reimbursement_categories' => [
        'transport' => ['label' => 'Transportasi', 'icon' => 'truck'],
        'meals' => ['label' => 'Makanan', 'icon' => 'wallet'],
        'travel' => ['label' => 'Perjalanan Dinas', 'icon' => 'briefcase'],
        'supplies' => ['label' => 'Perlengkapan', 'icon' => 'package'],
        'communication' => ['label' => 'Komunikasi', 'icon' => 'wallet'],
        'other' => ['label' => 'Lainnya', 'icon' => 'wallet'],
    ],
    'roles' => [
        'super-admin' => ['label' => 'Super Admin', 'permissions' => ['*']],
        'finance' => ['label' => 'Finance', 'permissions' => [
            'dashboard.view', 'quotations.view', 'costs.manage',
            'invoices.manage', 'payments.manage', 'journals.manage', 'reports.view',
            'financial.view', 'pricing.view', 'email.manage', 'activity.view',
        ]],
        'finance-manager' => ['label' => 'Finance Manager', 'permissions' => [
            'dashboard.view', 'customers.view', 'customers.approve', 'quotations.view', 'costs.manage', 'jobs.close',
            'invoices.manage', 'payments.manage', 'journals.manage', 'reports.view',
            'financial.view', 'pricing.view', 'email.manage', 'activity.view', 'users.view',
        ]],
        'sales-manager' => ['label' => 'Sales Manager', 'permissions' => [
            'dashboard.view', 'customers.view', 'customers.manage', 'quotations.view', 'quotations.manage', 'export-documents.manage',
            'quotations.approve', 'jobs.view', 'jobs.manage', 'master-data.manage', 'vendors.manage', 'pricing.manage', 'pricing.view',
        ]],
        'sales' => ['label' => 'Sales', 'permissions' => [
            'dashboard.view', 'customers.view', 'customers.manage', 'quotations.view', 'quotations.manage',
            'pricing.view',
        ]],
        'operational' => ['label' => 'Operation', 'permissions' => [
            'dashboard.view', 'quotations.view', 'quotations.manage', 'jobs.view', 'jobs.manage', 'jobs.confirm-do',
        ]],
        'customer-service' => ['label' => 'Customer Service', 'permissions' => [
            'dashboard.view', 'customers.view', 'quotations.view', 'quotations.manage', 'jobs.view', 'jobs.manage', 'jobs.confirm-do',
        ]],
        'management' => ['label' => 'Management', 'permissions' => ['dashboard.view']],
    ],
];
