@extends('layouts.app')
@section('title','Detail Customer')
@section('content')
<div class="page-heading"><div><p class="eyebrow">SALES & CUSTOMER</p><h1>{{ $customer->code }}</h1><p>{{ $customer->name }}</p></div><a class="text-link" href="{{ route('customers.index') }}">Kembali ke daftar</a></div>
@if($customer->trashed())<div class="info-note"><strong>Customer nonaktif.</strong> Tidak dapat dipilih untuk transaksi baru. <form method="POST" action="{{ route('customers.restore',$customer) }}" data-confirm="Aktifkan kembali customer ini?" class="inline-form">@csrf<input type="hidden" name="lock_version" value="{{ $customer->lock_version }}"><button class="text-link">Aktifkan kembali</button></form></div>@endif
<section class="panel"><div class="panel-heading"><h2>Informasi customer</h2>@if($customer->trashed())<span class="status-badge status-inactive">Nonaktif</span>@else<span class="status-badge status-active">Aktif</span>@endif</div>
<dl class="detail-grid"><div><dt>Kode customer</dt><dd>{{ $customer->code }}</dd></div><div><dt>Nama</dt><dd>{{ $customer->name }}</dd></div><div><dt>Kontak</dt><dd>{{ $customer->contact_name ?? '—' }}</dd></div><div><dt>Email</dt><dd>{{ $customer->email ?? '—' }}</dd></div><div><dt>Telepon</dt><dd>{{ $customer->phone ?? '—' }}</dd></div><div><dt>NPWP</dt><dd>{{ $customer->tax_number ?? '—' }}</dd></div><div><dt>Syarat pembayaran default</dt><dd>{{ config('operations.customer_payment_terms.'.$customer->default_payment_terms) ?? $customer->default_payment_terms ?? '—' }}</dd></div><div><dt>Alamat</dt><dd>{{ $customer->address ?? '—' }}</dd></div><div><dt>Dibuat</dt><dd>{{ $customer->created_at?->format('d/m/Y H:i') }} · Diperbarui {{ $customer->updated_at?->format('d/m/Y H:i') }}</dd></div></dl>
</section>
<div class="quote-actions"><a class="button button-secondary" href="{{ route('customers.edit',$customer) }}">Edit customer</a></div>
<section class="panel"><div class="panel-heading"><h2>Shipper / Consignee</h2><a class="text-link" href="{{ route('customer-contacts.index',['customer_id'=>$customer->id]) }}">Kelola di master</a></div>
<div class="table-scroll"><table><thead><tr><th>Tipe</th><th>Nama / Perusahaan</th><th>Kontak</th><th>Negara</th><th>Status</th></tr></thead><tbody>@forelse($customer->contacts as $contact)<tr><td><span class="status-badge status-{{ $contact->type }}">{{ \Illuminate\Support\Str::ucfirst($contact->type) }}</span></td><td><strong>{{ $contact->name }}</strong>@if($contact->company)<br><small>{{ $contact->company }}</small>@endif</td><td>{{ $contact->email ?? '—' }}<br><small>{{ $contact->phone ?? '' }}</small></td><td>{{ $contact->country ?? '—' }}</td><td>@if($contact->is_active)<span class="status-badge status-active">Aktif</span>@else<span class="status-badge status-inactive">Nonaktif</span>@endif</td></tr>@empty<tr><td colspan="5"><div class="empty-state"><h3>Belum ada kontak</h3><p>Tambahkan shipper/consignee pada form edit customer atau master Consignee / Shipper.</p></div></td></tr>@endforelse</tbody></table></div></section>
<section class="panel"><div class="panel-heading"><h2>Dokumen</h2><span class="subtle">NPWP & NIB</span></div>
@if($customer->documents->isNotEmpty())
<div class="table-scroll"><table><thead><tr><th>Jenis</th><th>Nama file</th><th>Ukuran</th><th>Tipe</th><th>Diunggah oleh</th><th>Diunggah pada</th><th>Aksi</th></tr></thead><tbody>@foreach($customer->documents as $document)<tr><td><span class="status-badge status-approved">{{ \Illuminate\Support\Str::upper($document->type) }}</span></td><td>{{ $document->original_name ?? $document->filename }}</td><td>@if($document->size){{ number_format($document->size / 1024, 0, ',', '.') }} KB@else—@endif</td><td>{{ $document->mime ?? '—' }}</td><td>{{ $document->uploader?->name ?? '—' }}</td><td>{{ $document->created_at?->format('d/m/Y H:i') }}</td><td><div class="action-group"><a class="text-link" href="{{ route('customers.documents.download',$document) }}">Unduh</a>@can('customers.manage')<form method="POST" action="{{ route('customers.documents.destroy',$document) }}" data-confirm="Hapus dokumen ini?">@csrf @method('DELETE')<button class="text-link danger">Hapus</button></form>@endcan</div></td></tr>@endforeach</tbody></table></div>
@else
<div class="empty-state"><x-icon name="file"/><h3>Belum ada dokumen</h3><p>Unggah NPWP/NIB pada form edit customer.</p></div>
@endif
</section>
@endsection