@extends('layouts.app')
@section('title',$quotation->exists?'Edit Quotation':'Buat Quotation')
@section('content')
<div class="page-heading"><div><p class="eyebrow">OPERASIONAL</p><h1>{{ $quotation->exists?'Edit quotation':'Buat quotation' }}</h1><p>Simpan penawaran sebagai Draft sebelum diajukan.</p></div><a class="text-link" href="{{ $quotation->exists?route('quotations.show',$quotation):route('quotations.index') }}">Kembali</a></div>
@if($customers->isEmpty())<div class="info-note">Belum ada customer aktif. <a class="text-link" href="{{ route('customers.create') }}">Tambahkan customer terlebih dahulu.</a></div>@endif
<section class="panel"><form class="data-form" data-quotation-form data-pricing-endpoint="{{ route('pricing.suggest-trucking') }}" method="POST" action="{{ $quotation->exists?route('quotations.update',$quotation):route('quotations.store') }}">@csrf @if($quotation->exists) @method('PUT') @endif<input type="hidden" name="lock_version" value="{{ old('lock_version',$quotation->lock_version ?? 0) }}">
@if($quotation->exists && $quotation->status->value === 'revision')<div class="info-note"><strong>Quotation sedang direvisi.</strong> Perbaiki sesuai catatan revisi lalu ajukan ulang. @if($quotation->revision_reason)Catatan: {{ $quotation->revision_reason }}.@endif</div>@endif
<div class="form-grid"><div class="field"><label for="customer_id">Customer <span class="required">*</span></label><select name="customer_id" id="customer_id" required><option value="">Pilih customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((string)old('customer_id',$quotation->customer_id)===(string)$customer->id)>{{ $customer->code }} — {{ $customer->name }}</option>@endforeach</select></div><div class="field"><label for="subject">Judul penawaran <span class="required">*</span></label><input id="subject" name="subject" value="{{ old('subject',$quotation->subject) }}" required maxlength="255" placeholder="Contoh: Pengiriman Jakarta – Surabaya"></div>
<div class="field"><label for="service_type">Jenis layanan</label><select id="service_type" name="service_type"><option value="">—</option>@foreach(config('operations.service_types') as $key=>$label)<option value="{{ $key }}" @selected(old('service_type',$quotation->service_type)===$key)>{{ $label }}</option>@endforeach</select></div><div class="field"><label for="origin">Asal</label><input id="origin" name="origin" value="{{ old('origin',$quotation->origin) }}" maxlength="120" placeholder="cth: Jakarta"></div>
<div class="field"><label for="destination">Tujuan</label><input id="destination" name="destination" value="{{ old('destination',$quotation->destination) }}" maxlength="120" placeholder="cth: Surabaya"></div><div class="field"><label for="payment_terms">Ketentuan pembayaran</label><select id="payment_terms" name="payment_terms"><option value="">—</option>@foreach(config('operations.customer_payment_terms') as $key=>$label)<option value="{{ $key }}" @selected(old('payment_terms',$quotation->payment_terms)===$key)>{{ $label }}</option>@endforeach</select></div>
<div class="field"><label for="currency">Mata uang</label><select id="currency" name="currency">@foreach(config('operations.currencies') as $key=>$label)<option value="{{ $key }}" @selected(old('currency',$quotation->currency ?? 'IDR')===$key)>{{ $label }}</option>@endforeach</select></div><div class="field"><label for="exchange_rate">Kurs</label><input id="exchange_rate" name="exchange_rate" type="number" min="0.01" step="0.01" value="{{ old('exchange_rate',$quotation->exchange_rate ?? 1) }}" max="999999999.99"></div>
<div class="field"><label for="shipper_name">Shipper (pengirim)</label><input id="shipper_name" name="shipper_name" value="{{ old('shipper_name',$quotation->shipper_name) }}" maxlength="160" placeholder="Nama pengirim"></div><div class="field"><label for="consignee_name">Consignee (penerima)</label><input id="consignee_name" name="consignee_name" value="{{ old('consignee_name',$quotation->consignee_name) }}" maxlength="160" placeholder="Nama penerima"></div>
<div class="field span-2"><label for="shipper_address">Alamat shipper</label><textarea id="shipper_address" name="shipper_address" rows="2" maxlength="5000">{{ old('shipper_address',$quotation->shipper_address) }}</textarea></div><div class="field span-2"><label for="consignee_address">Alamat consignee</label><textarea id="consignee_address" name="consignee_address" rows="2" maxlength="5000">{{ old('consignee_address',$quotation->consignee_address) }}</textarea></div>
<div class="field"><label for="tax_rate">Pajak (%)</label><input id="tax_rate" name="tax_rate" type="number" min="0" max="100" step="0.01" value="{{ old('tax_rate',$quotation->tax_rate ?? 0) }}"></div><div class="field"><label for="discount">Diskon (IDR)</label><input id="discount" name="discount" type="number" min="0" max="999999999.99" step="0.01" value="{{ old('discount',$quotation->discount ?? 0) }}"></div>
</div>
<div class="section-heading"><h2>Detail penawaran</h2><span class="subtle">Maksimal 100 item · nilai dalam IDR · kurs memakai weekly pricing</span></div>
<div data-items>@php $rows=old('items',$quotation->exists?$quotation->items->toArray():[[]]); @endphp @foreach($rows as $index=>$item) @include('quotations.item',compact('index','item')) @endforeach</div>
<template data-item-template>@include('quotations.item',['index'=>'__INDEX__','item'=>[]])</template>
<button class="button button-secondary" type="button" data-add-item>+ Tambah item</button>
<div class="summary-box" aria-live="polite"><div class="summary-row"><span>Total sementara</span><strong data-preview-total>Rp 0,00</strong></div><div class="summary-row"><span>Estimasi profit</span><strong data-preview-profit>Rp 0,00</strong></div><p class="form-help">Pajak, diskon, dan grand total dihitung saat disimpan.</p></div>
<div class="field"><label for="notes">Catatan / ketentuan penawaran</label><textarea name="notes" id="notes" rows="3" maxlength="5000">{{ old('notes',$quotation->notes) }}</textarea></div><div class="form-actions"><a class="button button-secondary" href="{{ route('quotations.index') }}">Batal</a><button class="button button-primary" @disabled($customers->isEmpty())>Simpan draft</button></div></form></section>
@endsection