@extends('layouts.app')
@section('title',$quotation->exists?'Edit Quotation':'Buat Quotation')
@section('content')
<div class="page-heading"><div><p class="eyebrow">OPERASIONAL</p><h1>{{ $quotation->exists?'Edit quotation':'Buat quotation' }}</h1><p>Simpan penawaran sebagai Draft sebelum diajukan.</p></div><a class="text-link" href="{{ $quotation->exists?route('quotations.show',$quotation):route('quotations.index') }}">Kembali</a></div>
@if($customers->isEmpty())<div class="info-note">Belum ada customer aktif. <a class="text-link" href="{{ route('customers.create') }}">Tambahkan customer terlebih dahulu.</a></div>@endif
<section class="panel"><form class="data-form" data-quotation-form method="POST" action="{{ $quotation->exists?route('quotations.update',$quotation):route('quotations.store') }}">@csrf @if($quotation->exists) @method('PUT') @endif<input type="hidden" name="lock_version" value="{{ old('lock_version',$quotation->lock_version ?? 0) }}">
<div class="form-grid"><div class="field"><label for="customer_id">Customer <span class="required">*</span></label><select name="customer_id" id="customer_id" required><option value="">Pilih customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}" @selected((string)old('customer_id',$quotation->customer_id)===(string)$customer->id)>{{ $customer->code }} — {{ $customer->name }}</option>@endforeach</select></div><div class="field"><label for="subject">Judul penawaran <span class="required">*</span></label><input id="subject" name="subject" value="{{ old('subject',$quotation->subject) }}" required maxlength="255" placeholder="Contoh: Pengiriman Jakarta – Surabaya"></div>
<div class="field"><label for="quotation_date">Tanggal quotation</label><input id="quotation_date" name="quotation_date" type="date" value="{{ old('quotation_date',$quotation->quotation_date?->format('Y-m-d') ?? now()->toDateString()) }}" required></div><div class="field"><label for="valid_until">Berlaku sampai</label><input id="valid_until" name="valid_until" type="date" value="{{ old('valid_until',$quotation->valid_until?->format('Y-m-d') ?? now()->addDays(30)->toDateString()) }}" required></div></div>
<div class="section-heading"><h2>Detail penawaran</h2><span class="subtle">Maksimal 100 item · IDR</span></div>
<div data-items>@php $rows=old('items',$quotation->exists?$quotation->items->toArray():[[]]); @endphp @foreach($rows as $index=>$item) @include('quotations.item',compact('index','item')) @endforeach</div>
<template data-item-template>@include('quotations.item',['index'=>'__INDEX__','item'=>[]])</template>
<button class="button button-secondary" type="button" data-add-item>+ Tambah item</button>
<div class="summary-box" aria-live="polite"><div class="summary-row"><span>Total sementara</span><strong data-preview-total>Rp 0,00</strong></div><div class="summary-row"><span>Estimasi profit</span><strong data-preview-profit>Rp 0,00</strong></div><p class="form-help">Total sebelum pajak. Hasil akhir dihitung saat disimpan.</p></div>
<div class="field"><label for="notes">Catatan / ketentuan penawaran</label><textarea name="notes" id="notes" rows="3" maxlength="5000">{{ old('notes',$quotation->notes) }}</textarea></div><div class="form-actions"><a class="button button-secondary" href="{{ route('quotations.index') }}">Batal</a><button class="button button-primary" @disabled($customers->isEmpty())>Simpan draft</button></div></form></section>
@endsection
