@extends('layouts.app')
@section('title','Detail Quotation')
@section('content')
<div class="page-heading"><div><p class="eyebrow">QUOTATION</p><h1>{{ $quotation->number }}</h1><p>{{ $quotation->subject }}</p></div><a class="text-link" href="{{ route('quotations.index') }}">Kembali ke daftar</a></div>
<section class="panel"><div class="panel-heading"><h2>Informasi penawaran</h2><span class="status-badge status-{{ $quotation->status->value }}">{{ $quotation->status->label() }}</span></div>
<dl class="detail-grid"><div><dt>Customer</dt><dd><strong>{{ $quotation->customer_snapshot['name'] }}</strong><br>{{ $quotation->customer_snapshot['code'] }} @if($quotation->customer->trashed())<span class="count-badge">Diarsipkan</span>@endif</dd></div><div><dt>Tanggal quotation</dt><dd>{{ $quotation->quotation_date->format('d/m/Y') }}</dd></div><div><dt>Berlaku sampai</dt><dd>{{ $quotation->valid_until->format('d/m/Y') }}</dd></div><div><dt>Kontak</dt><dd>{{ $quotation->customer_snapshot['contact_name'] ?? '—' }}<br>{{ $quotation->customer_snapshot['email'] ?? '' }}<br>{{ $quotation->customer_snapshot['phone'] ?? '' }}</dd></div><div><dt>Alamat customer</dt><dd>{{ $quotation->customer_snapshot['address'] ?? '—' }}</dd></div><div><dt>Dibuat oleh</dt><dd>{{ $quotation->creator?->name ?? '—' }}<br>{{ $quotation->created_at->format('d/m/Y H:i') }}</dd></div></dl>
<div class="table-scroll"><table class="quote-detail-table"><thead><tr><th>Uraian</th><th>Jenis</th><th>Jumlah / Satuan</th><th class="money">Modal / unit</th><th class="money">Jual / unit</th><th class="money">Total tagihan</th></tr></thead><tbody>@foreach($quotation->items as $item)@php $snap = $item->pricing_snapshot ?? []; $fc = strtoupper($snap['currency'] ?? 'IDR'); @endphp<tr><td>{{ $item->description }}@if($item->pricing_source === 'trucking')<br><small class="muted-cell">Tarif trucking · {{ $snap['port_origin'] ?? '' }} → {{ $snap['destination'] ?? '' }} · {{ strtoupper($item->container_type) }} @if($item->overweight) · OVERWEIGHT @endif @if($fc !== 'IDR') · {{ $fc }} {{ \App\Support\Money::format($snap['price'] ?? 0) }} @if(!empty($snap['vendor_name'])) · {{ $snap['vendor_name'] }} @endif @endif</small> @elseif($item->container_type)<br><small class="muted-cell">{{ strtoupper($item->container_type) }} @if($item->overweight) · OVERWEIGHT @endif @if($item->gross_weight !== null) · BW {{ \App\Support\Money::format($item->gross_weight) }} kg @endif @if($item->volume !== null) · {{ $item->volume }} m³ @endif</small> @endif</td><td>{{ ucfirst($item->type) }}</td><td>{{ \App\Support\Money::format($item->quantity) }} {{ $item->unit }}</td><td class="money">{{ \App\Support\Money::format($item->unit_cost) }}</td><td class="money">{{ \App\Support\Money::format($item->unit_price) }}</td><td class="money">{{ \App\Support\Money::format($item->total_price) }}</td></tr>@endforeach</tbody></table></div>
@if($quotation->items->contains(fn ($item) => $item->pricing_source === 'trucking' || $item->currency !== 'IDR'))<p class="form-help">Nilai semua item sudah dikonversi ke IDR. Item mata uang asing memakai kurs weekly pricing aktif pada tanggal quotation.</p>@endif
<div class="summary-box">@foreach(['total_temporary'=>'Temporary','total_provision_cost'=>'Modal provision','total_provision_sell'=>'Nilai jual provision','profit'=>'Estimasi profit'] as $field=>$label)<div class="summary-row"><span>{{ $label }}</span><strong>Rp {{ \App\Support\Money::format($quotation->$field) }}</strong></div>@endforeach<div class="summary-row"><span>Margin provision</span><strong>{{ \App\Support\Money::format($quotation->margin) }}%</strong></div><div class="summary-row summary-total"><span>Total sebelum pajak</span><strong>Rp {{ \App\Support\Money::format($quotation->subtotal) }}</strong></div></div>
@if($quotation->notes)<div class="detail-notes"><strong>Catatan</strong><br>{{ $quotation->notes }}</div>@endif
@if($quotation->approved_at)<div class="detail-notes">Disetujui {{ $quotation->approver?->name }} · {{ $quotation->approved_at->format('d/m/Y H:i') }}</div>@endif
@if($quotation->rejection_reason)<div class="detail-notes"><strong>Alasan penolakan</strong><br>{{ $quotation->rejection_reason }}</div>@endif
</section>
<div class="quote-actions">
@can('update',$quotation)<a class="button button-secondary" href="{{ route('quotations.edit',$quotation) }}">Edit draft</a>@endcan
@can('submit',$quotation)<form method="POST" action="{{ route('quotations.submit',$quotation) }}" data-confirm="Ajukan quotation ini? Draft tidak dapat diedit setelah diajukan.">@csrf<input type="hidden" name="lock_version" value="{{ $quotation->lock_version }}"><button class="button button-primary">Ajukan quotation</button></form>@endcan
@can('approve',$quotation)<form method="POST" action="{{ route('quotations.approve',$quotation) }}" data-confirm="Setujui quotation ini?">@csrf<input type="hidden" name="lock_version" value="{{ $quotation->lock_version }}"><button class="button button-primary">Setujui quotation</button></form>@endcan
@can('convert',$quotation)<form method="POST" action="{{ route('quotations.convert',$quotation) }}" data-confirm="Buat Job Order Draft dari quotation ini? Konversi hanya dapat dilakukan satu kali.">@csrf<input type="hidden" name="lock_version" value="{{ $quotation->lock_version }}"><button class="button button-primary">Konversi ke Job Order <x-icon name="arrow"/></button></form>@endcan
@if($quotation->job)<a class="button button-primary" href="{{ route('jobs.show',$quotation->job) }}">Lihat {{ $quotation->job->number }} <x-icon name="arrow"/></a>@endif
</div>
@can('reject',$quotation)<section class="panel"><form class="transition-form" method="POST" action="{{ route('quotations.reject',$quotation) }}" data-confirm="Tolak quotation ini? Quotation yang ditolak tidak dapat dikonversi.">@csrf<input type="hidden" name="lock_version" value="{{ $quotation->lock_version }}"><label for="reason">Alasan penolakan</label><textarea id="reason" name="reason" required maxlength="1000" rows="2" placeholder="Jelaskan alasan penawaran ditolak">{{ old('reason') }}</textarea><button class="button button-danger">Tolak quotation</button></form></section>@endcan
@endsection
