@extends('layouts.app')
@section('title','Detail Quotation')
@section('content')
<div class="page-heading"><div><p class="eyebrow">QUOTATION</p><h1>{{ $quotation->number }}</h1><p>{{ $quotation->subject }}</p></div><a class="text-link" href="{{ route('quotations.index') }}">Kembali ke daftar</a></div>
<section class="panel"><div class="panel-heading"><h2>Informasi penawaran</h2><span class="status-badge status-{{ $quotation->status->value }}">{{ $quotation->status->label() }}</span></div>
<dl class="detail-grid"><div><dt>Customer</dt><dd><strong>{{ $quotation->customer_snapshot['name'] }}</strong><br>{{ $quotation->customer_snapshot['code'] }} @if($quotation->customer->trashed())<span class="count-badge">Diarsipkan</span>@endif</dd></div><div><dt>Tanggal quotation</dt><dd>{{ $quotation->quotation_date->format('d/m/Y') }}</dd></div><div><dt>Berlaku sampai</dt><dd>{{ $quotation->valid_until->format('d/m/Y') }}</dd></div><div><dt>Kontak</dt><dd>{{ $quotation->customer_snapshot['contact_name'] ?? '—' }}<br>{{ $quotation->customer_snapshot['email'] ?? '' }}<br>{{ $quotation->customer_snapshot['phone'] ?? '' }}</dd></div><div><dt>Alamat customer</dt><dd>{{ $quotation->customer_snapshot['address'] ?? '—' }}</dd></div><div><dt>Dibuat oleh</dt><dd>{{ $quotation->creator?->name ?? '—' }}<br>{{ $quotation->created_at->format('d/m/Y H:i') }}</dd></div>
@if($quotation->sales)<div><dt>Sales PIC</dt><dd>{{ $quotation->sales->name }}</dd></div>@endif
@if($quotation->service_type)<div><dt>Services (Layanan)</dt><dd>{{ \App\Models\ServiceType::label($quotation->service_type) }}</dd></div>@endif
@if($quotation->terms_of_delivery)<div><dt>Terms of Delivery</dt><dd>{{ config('operations.terms_of_delivery.'.$quotation->terms_of_delivery) ?? $quotation->terms_of_delivery }}</dd></div>@endif
@if($quotation->cargo_qty)<div><dt>Quantity (Shipment)</dt><dd>{{ $quotation->cargo_qty }}</dd></div>@endif
@if($quotation->weight_meas)<div><dt>Weight / Meas</dt><dd>{{ $quotation->weight_meas }}</dd></div>@endif
@if($quotation->commodity)<div><dt>Commodity</dt><dd>{{ $quotation->commodity }}</dd></div>@endif
@if($quotation->origin || $quotation->destination)<div><dt>Port of Loading → Discharge</dt><dd>{{ $quotation->origin ?? '—' }} → {{ $quotation->destination ?? '—' }}</dd></div>@endif
@if($quotation->currency)<div><dt>Mata uang</dt><dd>{{ $quotation->currency }} @if($quotation->currency !== 'IDR' && $quotation->exchange_rate) · kurs {{ \App\Support\Money::format($quotation->exchange_rate) }}@endif</dd></div>@endif
@if($quotation->payment_terms)<div><dt>Ketentuan pembayaran</dt><dd>{{ config('operations.customer_payment_terms.'.$quotation->payment_terms) ?? '—' }}</dd></div>@endif
@if($quotation->shipper_name)<div><dt>Shipper</dt><dd>{{ $quotation->shipper_name }}<br><small>{{ $quotation->shipper_address ?? '' }}</small></dd></div>@endif
@if($quotation->consignee_name)<div><dt>Consignee</dt><dd>{{ $quotation->consignee_name }}<br><small>{{ $quotation->consignee_address ?? '' }}</small></dd></div>@endif
</dl>
@can('financial.view')
<div class="table-scroll"><table class="quote-detail-table"><thead><tr><th>Uraian</th><th>Note</th><th>Mata Uang</th><th>Jenis</th><th>Jumlah / Satuan</th><th class="money">Modal / unit</th><th class="money">Jual / unit</th><th class="money">Total tagihan (IDR)</th></tr></thead><tbody>@foreach($quotation->items as $item)@php $snap = $item->pricing_snapshot ?? []; $fc = strtoupper($snap['currency'] ?? ($item->currency ?? 'IDR')); @endphp<tr><td>{{ $item->description }}@if($item->pricing_source === 'trucking')<br><small class="muted-cell">Tarif trucking · {{ $snap['port_origin'] ?? '' }} → {{ $snap['destination'] ?? '' }} · {{ strtoupper($item->container_type) }} @if($item->overweight) · OVERWEIGHT @endif @if($fc !== 'IDR') · {{ $fc }} {{ \App\Support\Money::format($snap['price'] ?? 0) }} @if(!empty($snap['vendor_name'])) · {{ $snap['vendor_name'] }} @endif @endif</small> @elseif($item->container_type)<br><small class="muted-cell">{{ strtoupper($item->container_type) }} @if($item->overweight) · OVERWEIGHT @endif @if($item->gross_weight !== null) · BW {{ \App\Support\Money::format($item->gross_weight) }} kg @endif @if($item->volume !== null) · {{ $item->volume }} m³ @endif</small> @endif</td><td>{{ $item->note ?? '—' }}</td><td><span class="status-badge" style="font-size:11px;">{{ $item->currency ?? 'IDR' }}</span>@if(($item->currency ?? 'IDR') !== 'IDR' && $item->exchange_rate)<br><small class="subtle">Kurs {{ \App\Support\Money::format($item->exchange_rate) }}</small>@endif</td><td>{{ ucfirst($item->type) }}</td><td>{{ \App\Support\Money::format($item->quantity) }} {{ $item->unit }}</td><td class="money">@if($item->unit_cost !== null){{ ($item->currency ?? 'IDR') !== 'IDR' ? ($item->currency.' '.\App\Support\Money::format($item->unit_cost)) : ('Rp '.\App\Support\Money::format($item->unit_cost)) }}@else — @endif</td><td class="money">{{ ($item->currency ?? 'IDR') !== 'IDR' ? ($item->currency.' '.\App\Support\Money::format($item->unit_price)) : ('Rp '.\App\Support\Money::format($item->unit_price)) }}</td><td class="money">Rp {{ \App\Support\Money::format($item->total_price) }}</td></tr>@endforeach</tbody></table></div>
@if($quotation->items->contains(fn ($item) => $item->pricing_source === 'trucking' || $item->currency !== 'IDR'))<p class="form-help">Nilai item valuta asing dikonversikan ke IDR sesuai kurs yang ditentukan pada penawaran.</p>@endif
<div class="summary-box">@foreach(['total_temporary'=>'Temporary','total_provision_cost'=>'Modal provision','total_provision_sell'=>'Nilai jual provision','profit'=>'Estimasi profit'] as $field=>$label)<div class="summary-row"><span>{{ $label }}</span><strong>Rp {{ \App\Support\Money::format($quotation->$field) }}</strong></div>@endforeach<div class="summary-row"><span>Margin provision</span><strong>{{ \App\Support\Money::format($quotation->margin) }}%</strong></div><div class="summary-row summary-total"><span>Total sebelum pajak</span><strong>Rp {{ \App\Support\Money::format($quotation->subtotal) }}</strong></div></div>
@else
<div class="table-scroll"><table class="quote-detail-table"><thead><tr><th>Uraian</th><th>Note</th><th>Mata Uang</th><th>Jenis</th><th>Jumlah / Satuan</th><th class="money">Jual / unit</th><th class="money">Total tagihan (IDR)</th></tr></thead><tbody>@foreach($quotation->items as $item)<tr><td>{{ $item->description }}</td><td>{{ $item->note ?? '—' }}</td><td><span class="status-badge" style="font-size:11px;">{{ $item->currency ?? 'IDR' }}</span>@if(($item->currency ?? 'IDR') !== 'IDR' && $item->exchange_rate)<br><small class="subtle">Kurs {{ \App\Support\Money::format($item->exchange_rate) }}</small>@endif</td><td>{{ ucfirst($item->type) }}</td><td>{{ \App\Support\Money::format($item->quantity) }} {{ $item->unit }}</td><td class="money">{{ ($item->currency ?? 'IDR') !== 'IDR' ? ($item->currency.' '.\App\Support\Money::format($item->unit_price)) : ('Rp '.\App\Support\Money::format($item->unit_price)) }}</td><td class="money">Rp {{ \App\Support\Money::format($item->total_price) }}</td></tr>@endforeach</tbody></table></div>
<div class="summary-box"><div class="summary-row summary-total"><span>Total tagihan</span><strong>Rp {{ \App\Support\Money::format($quotation->subtotal) }}</strong></div></div>
@endcan
@if($quotation->discount != 0 || $quotation->tax_rate != 0)
<div class="summary-box"><div class="summary-row"><span>Diskon</span><strong>− Rp {{ \App\Support\Money::format($quotation->discount) }}</strong></div><div class="summary-row"><span>Pajak ({{ \App\Support\Money::format($quotation->tax_rate) }}%)</span><strong>Rp {{ \App\Support\Money::format($quotation->tax_amount) }}</strong></div><div class="summary-row summary-total"><span>Grand total</span><strong>Rp {{ \App\Support\Money::format($quotation->grand_total) }}</strong></div></div>
@endif
@if($quotation->notes)<div class="detail-notes"><strong>Catatan</strong><br>{{ $quotation->notes }}</div>@endif
@if($quotation->approved_at)<div class="detail-notes">Disetujui {{ $quotation->approver?->name }} · {{ $quotation->approved_at->format('d/m/Y H:i') }}</div>@endif
@if($quotation->revised_at)<div class="detail-notes"><strong>Direvisi</strong><br>{{ $quotation->revisedBy?->name }} · {{ $quotation->revised_at->format('d/m/Y H:i') }}<br>{{ $quotation->revision_reason }}</div>@endif
@if($quotation->rejection_reason)<div class="detail-notes"><strong>Alasan penolakan</strong><br>{{ $quotation->rejection_reason }}</div>@endif
</section>
<div class="quote-actions">
@can('update',$quotation)<a class="button button-secondary" href="{{ route('quotations.edit',$quotation) }}">Edit draft</a>@endcan
<form method="POST" action="{{ route('quotations.duplicate',$quotation) }}" data-confirm="Buat salinan draft baru dari quotation ini?">@csrf<button class="button button-secondary">Duplikat draft</button></form>
<a class="button button-secondary" href="{{ route('quotations.preview',$quotation) }}" target="_blank">🖨 Preview PDF</a>
@can('submit',$quotation)<form method="POST" action="{{ route('quotations.submit',$quotation) }}" data-confirm="Ajukan quotation ini? Draft tidak dapat diedit setelah diajukan.">@csrf<input type="hidden" name="lock_version" value="{{ $quotation->lock_version }}"><button class="button button-primary">Ajukan quotation</button></form>@endcan
@can('approve',$quotation)<form method="POST" action="{{ route('quotations.approve',$quotation) }}" data-confirm="Setujui quotation ini?">@csrf<input type="hidden" name="lock_version" value="{{ $quotation->lock_version }}"><button class="button button-primary">Setujui quotation</button></form>@endcan
@can('convert',$quotation)<form method="POST" action="{{ route('quotations.convert',$quotation) }}" data-confirm="Buat Job Order Draft dari quotation ini? Konversi hanya dapat dilakukan satu kali.">@csrf<input type="hidden" name="lock_version" value="{{ $quotation->lock_version }}"><button class="button button-primary">Konversi ke Job Order <x-icon name="arrow"/></button></form>@endcan
@if($quotation->job)<a class="button button-primary" href="{{ route('jobs.show',$quotation->job) }}">Lihat {{ $quotation->job->number }} <x-icon name="arrow"/></a>@endif
</div>
@can('revise',$quotation)<section class="panel"><form class="transition-form" method="POST" action="{{ route('quotations.revise',$quotation) }}" data-confirm="Minta revisi quotation? Sales dapat mengedit ulang quotation setelah direvisi.">@csrf<input type="hidden" name="lock_version" value="{{ $quotation->lock_version }}"><label for="revision">Catatan revisi</label><textarea id="revision" name="reason" required maxlength="1000" rows="2" placeholder="Jelaskan bagian yang perlu diperbaiki">{{ old('reason') }}</textarea><button class="button button-secondary">Minta revisi</button></form></section>@endcan
@can('reject',$quotation)<section class="panel"><form class="transition-form" method="POST" action="{{ route('quotations.reject',$quotation) }}" data-confirm="Tolak quotation ini? Quotation yang ditolak tidak dapat dikonversi.">@csrf<input type="hidden" name="lock_version" value="{{ $quotation->lock_version }}"><label for="reason">Alasan penolakan</label><textarea id="reason" name="reason" required maxlength="1000" rows="2" placeholder="Jelaskan alasan penawaran ditolak">{{ old('reason') }}</textarea><button class="button button-danger">Tolak quotation</button></form></section>@endcan
@if($quotation->statusHistory->isNotEmpty())
<section class="panel"><div class="panel-heading"><h2>Riwayat status</h2></div><ol class="approval-timeline">@foreach($quotation->statusHistory as $event)<li><span></span><div><strong>@if($event->from_status){{ \App\Enums\QuotationStatus::tryFrom($event->from_status)?->label() ?? $event->from_status }} → {{ \App\Enums\QuotationStatus::tryFrom($event->to_status)?->label() ?? $event->to_status }}@else Dibuat → {{ \App\Enums\QuotationStatus::tryFrom($event->to_status)?->label() ?? $event->to_status }}@endif</strong><p>{{ $event->user?->name ?? 'System' }} · {{ $event->created_at->format('d/m/Y H:i') }}@if($event->note)<br>{{ $event->note }}@endif</p></div></li>@endforeach</ol></section>
@endif
@endsection
