@extends('layouts.app') @section('title','Closing Job') @section('content')
<div class="page-heading"><div><p class="eyebrow">{{ $job->number }}</p><h1>Konfirmasi closing</h1><p>{{ $job->subject }}</p></div><a class="text-link" href="{{ route('closing.index') }}">Kembali</a></div>
@if($job->costs()->count()===0||$job->costs()->where('status','draft')->exists())<div class="flash-error">Closing belum siap: job harus memiliki biaya dan seluruh biaya harus Final.</div>@endif
<section class="panel form-panel"><div class="detail-grid"><div><dt>Temporary</dt><dd>Rp {{ \App\Support\Money::format($summary['temporary']) }}</dd></div><div><dt>Modal provision</dt><dd>Rp {{ \App\Support\Money::format($summary['provision_cost']) }}</dd></div><div><dt>Jual provision</dt><dd>Rp {{ \App\Support\Money::format($summary['provision_sell']) }}</dd></div><div><dt>Profit</dt><dd>Rp {{ \App\Support\Money::format($summary['profit']) }}</dd></div><div><dt>Subtotal</dt><dd>Rp {{ \App\Support\Money::format($summary['subtotal']) }}</dd></div></div>
<form class="data-form" method="POST" action="{{ route('closing.store',$job) }}" data-confirm="Tutup job ini? Invoice dan jurnal Posted akan dibuat dan tidak dapat dibatalkan langsung.">@csrf<input type="hidden" name="lock_version" value="{{ $job->lock_version }}"><div class="info-note">Closing membuat snapshot historis, invoice Issued, jurnal kapitalisasi biaya, dan jurnal pengakuan pendapatan/HPP.@if(($job->quotation_snapshot['currency'] ?? 'IDR') !== 'IDR') Mata uang invoice: <strong>{{ $job->quotation_snapshot['currency'] }} (kurs {{ $job->quotation_snapshot['exchange_rate'] ?? '1' }})</strong>. Nilai buku tetap dalam Rupiah.@endif</div><div class="form-grid"><div class="field"><label>Tanggal closing</label><input type="date" name="closing_date" value="{{ old('closing_date',today()->toDateString()) }}" min="{{ $job->job_date->format('Y-m-d') }}" max="{{ today()->toDateString() }}" required></div><div class="field"><label>Jatuh tempo invoice</label><input type="date" name="due_date" value="{{ old('due_date',today()->addDays(30)->toDateString()) }}" required></div><div class="field"><label>Sumber dana biaya</label><select name="funding_account" required><option value="bank">Bank</option><option value="cash" @selected(old('funding_account')==='cash')>Kas</option></select></div><div class="field"><label>Pajak (Rp)</label><input type="number" name="tax" min="0" max="999999999.99" step=".01" value="{{ old('tax','0') }}" required></div>
@if(($job->quotation_snapshot['currency'] ?? 'IDR') !== 'IDR')
<div class="field"><label>Kurs override (opsional)</label><input type="number" name="exchange_rate_override" min="0.000001" max="999999999.99" step=".01" value="{{ old('exchange_rate_override') }}" placeholder="Default {{ $job->quotation_snapshot['exchange_rate'] ?? 1 }}" title="Ganti kurs quotation untuk invoice ini; nilai buku tetap dalam Rupiah."></div>
@endif
</div><div class="form-actions"><button class="button button-primary" @disabled($job->costs()->count()===0||$job->costs()->where('status','draft')->exists())>Close job dan buat invoice</button></div></form></section>
@endsection
