@extends('layouts.app')
@section('title',$truckingPrice->exists?'Edit Trucking Price':'Tambah Trucking Price')
@section('content')
<div class="page-heading"><div><p class="eyebrow">PRICING</p><h1>{{ $truckingPrice->exists?'Edit trucking price':'Tambah trucking price' }}</h1><p>Harga trucking untuk rute dan tipe kontainer tertentu.</p></div><a class="text-link" href="{{ route('pricing.trucking.index') }}">Kembali ke daftar</a></div>
<section class="panel form-panel"><form class="data-form" method="POST" action="{{ $truckingPrice->exists?route('pricing.trucking.update',$truckingPrice):route('pricing.trucking.store') }}">@csrf @if($truckingPrice->exists) @method('PUT') @endif
<input type="hidden" name="lock_version" value="{{ old('lock_version',$truckingPrice->lock_version ?? 0) }}">
<div class="form-grid">
<div class="field"><label for="port_origin">Pelabuhan asal <span class="required">*</span></label><input id="port_origin" name="port_origin" value="{{ old('port_origin',$truckingPrice->port_origin) }}" placeholder="cth. Tanjung Priok" required></div>
<div class="field"><label for="destination">Tujuan <span class="required">*</span></label><input id="destination" name="destination" value="{{ old('destination',$truckingPrice->destination) }}" placeholder="cth. Bandung / Surabaya" required></div>
<div class="field"><label for="container_type">Tipe kontainer / armada <span class="required">*</span></label><select id="container_type" name="container_type" required><option value="">Pilih tipe</option>@foreach(config('operations.trucking_container_types') as $value=>$label)<option value="{{ $value }}" @selected(old('container_type',$truckingPrice->container_type)===$value)>{{ $label }}</option>@endforeach</select></div>
<div class="field"><label for="overweight">Kategori berat <span class="required">*</span></label><select id="overweight" name="overweight"><option value="0" @selected(!$truckingPrice->exists || !$truckingPrice->overweight)>Normal</option><option value="1" @selected($truckingPrice->exists && $truckingPrice->overweight)>Overweight</option></select><small class="form-help">Pilih Normal atau Overweight sesuai tarif.</small></div>
<div class="field"><label for="vendor_id">Vendor Trucking <span class="required">*</span></label><select id="vendor_id" name="vendor_id" required><option value="">Pilih Vendor Trucking</option>@foreach($vendors as $vendor)<option value="{{ $vendor->id }}" @selected((int) old('vendor_id',$truckingPrice->vendor_id)===$vendor->id)>{{ $vendor->name }}</option>@endforeach</select></div>
<div class="field"><label for="currency">Mata uang <span class="required">*</span></label><select id="currency" name="currency" required>@foreach(config('operations.currencies') as $code=>$label)<option value="{{ $code }}" @selected(old('currency',$truckingPrice->currency)===$code)>{{ $label }}</option>@endforeach</select></div>
<div class="field"><label for="price">Modal / Cost (Beli) <span class="required">*</span></label><input id="price" type="text" inputmode="decimal" name="price" value="{{ old('price',$truckingPrice->exists?number_format((float) $truckingPrice->price, 2, '.', ''):'') }}" placeholder="0.00" required></div>
<div class="field"><label for="selling_price">Harga Jual (Selling Price)</label><input id="selling_price" type="text" inputmode="decimal" name="selling_price" value="{{ old('selling_price',$truckingPrice->exists && $truckingPrice->selling_price?number_format((float) $truckingPrice->selling_price, 2, '.', ''):'') }}" placeholder="0.00"></div>
<div class="field"><label for="effective_date">Tanggal berlaku <span class="required">*</span></label><input id="effective_date" type="date" name="effective_date" value="{{ old('effective_date',$truckingPrice->effective_date?->format('Y-m-d') ?? today()->format('Y-m-d')) }}" required></div>
<div class="field"><label for="is_active">Status</label><select id="is_active" name="is_active"><option value="1" @selected(!$truckingPrice->exists || $truckingPrice->is_active)>Aktif</option><option value="0" @selected($truckingPrice->exists && !$truckingPrice->is_active)>Nonaktif</option></select></div>
</div>
<div class="form-actions"><a class="button button-secondary" href="{{ route('pricing.trucking.index') }}">Batal</a><button class="button button-primary">Simpan trucking price</button></div></form></section>
@endsection
