@extends('layouts.app')
@section('title','Kalkulator Pajak')
@section('content')
<div class="page-heading"><div><p class="eyebrow">KALKULATOR</p><h1>Hitung Pajak Impor</h1></div>    <a class="button button-secondary" href="{{ route('calculators.index') }}">← Kembali</a></div>
<section class="panel form-panel calculator-panel calc-detail-card">
<div class="calc-detail-head"><div class="calc-icon-badge emerald"><x-icon name="file"/></div><h2>Input Pajak</h2></div>
<form class="data-form calculator-form" id="tax-form"><div class="form-grid"><div class="field span-2"><label for="base_amount">Nilai Pabean / CIF (IDR)</label><input id="base_amount" type="text" inputmode="decimal" value="10000000" required></div><div class="field"><label for="import_duty_rate">Tarif Bea Masuk / BM (%)</label><input id="import_duty_rate" type="number" min="0" max="100" step="0.01" value="0" required></div><div class="field"><label for="vat_rate">Tarif PPN (%)</label><select id="vat_rate"><option value="11">11%</option><option value="12">12%</option></select></div><div class="field"><label for="pph_rate">Tarif PPh (%)</label><input id="pph_rate" type="number" min="0" max="100" step="0.01" value="2.5" required></div></div><p class="form-help">BM = Nilai Pabean × Tarif BM. PPN dan PPh = (Nilai Pabean + BM) × tarif masing-masing.</p><div class="form-actions"><button class="button button-primary" type="submit">Hitung pajak</button></div></form>
<div class="cost-summary-body calc-result-card" id="tax-result" hidden><div class="stats-grid"><div class="stat-card"><p>Bea Masuk</p><strong id="r-import-duty">—</strong></div><div class="stat-card"><p>PPN</p><strong id="r-vat">—</strong></div><div class="stat-card"><p>PPh</p><strong id="r-withholding">—</strong></div><div class="stat-card"><p>Total pajak</p><strong id="r-total-tax">—</strong></div><div class="stat-card"><p>Total setelah pajak</p><strong id="r-total">—</strong></div></div></div></section>
<script>
(function(){const form=document.getElementById('tax-form'),result=document.getElementById('tax-result');form.addEventListener('submit',e=>{e.preventDefault();const p=new URLSearchParams({base_amount:document.getElementById('base_amount').value,import_duty_rate:document.getElementById('import_duty_rate').value,vat_rate:document.getElementById('vat_rate').value,pph_rate:document.getElementById('pph_rate').value});fetch('/api/calculators/tax?'+p,{headers:{'X-Requested-With':'XMLHttpRequest'}}).then(r=>r.json().then(d=>({ok:r.ok,d}))).then(({ok,d})=>{result.hidden=!ok;if(!ok){window.appAlert('Periksa kembali input nilai dasar dan tarif pajak.','Input Tidak Valid',{type:'warning'});return}const idr=new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:2});document.getElementById('r-import-duty').textContent=idr.format(d.import_duty);document.getElementById('r-vat').textContent=idr.format(d.vat)+' ('+d.vat_rate+'%)';document.getElementById('r-withholding').textContent=idr.format(d.withholding)+' ('+d.withholding_rate+'%)';document.getElementById('r-total-tax').textContent=idr.format(d.total_tax);document.getElementById('r-total').textContent=idr.format(d.total)})})})();
</script>
@endsection
